app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: registry.hub.docker.com/jammsen/palworld-dedicated-server
            tag: latest
          env:
            ALWAYS_UPDATE_ON_START: true
            MAX_PLAYERS: 32
            MULTITHREAD_ENABLED: true
            COMMUNITY_SERVER: false
            RCON_ENABLED: true
            RCON_PORT: 25575
            PUBLIC_PORT: 8211
            PUBLIC_IP: 84.193.166.67
            SERVER_NAME: bambi-palworld
            SERVER_DESCRIPTION: Palworld-Dedicated-Server running in Docker by Bambi
            SERVER_PASSWORD: bambi4ever
            ADMIN_PASSWORD: bambi4ever 
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
  service:
    main:
      ports:
        http:
          port: 8211
      type: LoadBalancer
      loadBalancerIP: 192.168.0.69
  persistence:
    palworld:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 30Gi
      mountpath: /palworld
      storageClass: local-path-ssd
  ingress:
    main:
      enabled: true
      annotations:
        nginx.org/websocket-services: "palworld"
        cert-manager.io/cluster-issuer: "issuer"
      hosts:
        - host: &host palworld.intropin.be
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: 8211
                protocol: UDP
      tls:
        - secretName: palworld-letsencrypt-certificate
          hosts: [*host]
