app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: registry.hub.docker.com/thijsvanloef/palworld-server-docker
            tag: latest
          env:
            PUID: 1000
            PORT: 8211
            PLAYERS: 16
            MULTITHREADING: true
            ENABLE_RCON: true
            RCON_PORT: 25575
            ADMIN_PASSWORD: "bambi4ever"
            COMMUNITY: false
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
  service:
    main:
      ports:
        http:
          port: 8211
          protocol: UDP
        rcon:
          port: 25575
          protocol: UDP
        query:
          port: 27015
          protocol: UDP
      type: LoadBalancer
      loadBalancerIP: 192.168.0.69
  persistence:
    palworld:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 30Gi
      mountpath: /palworld
      storageClass: local-path-ssd
