app-template:
  controllers:
    main:
      replicas: 1
      containers:
        main:
          image:
            repository: registry.hub.docker.com/thijsvanloef/palworld-server-docker
            tag: latest
          env:
            PUID: 1000
            PORT: 8211
            PLAYERS: 16
            MULTITHREADING: true
            ADMIN_PASSWORD: "bambi4ever"
            COMMUNITY: false
            # PLAYERS: 
            # PUBLIC_IP: 
            # PUBLIC_PORT: 
            # DIFFICULTY: 
            # DAYTIME_SPEEDRATE: 
            # NIGHTTIME_SPEEDRATE: 
            EXP_RATE: 10
            # PAL_CAPTURE_RATE: 
            # PAL_SPAWN_NUM_RATE: 
            # PAL_DAMAGE_RATE_ATTACK: 
            # PAL_DAMAGE_RATE_DEFENSE: 
            # PLAYER_DAMAGE_RATE_ATTACK: 
            # PLAYER_DAMAGE_RATE_DEFENSE: 
            # PLAYER_STOMACH_DECREASE_RATE: 
            # PLAYER_STAMINA_DECREASE_RATE: 
            # PLAYER_AUTO_HP_REGEN_RATE: 
            # PLAYER_AUTO_HP_REGEN_RATE_IN_SLEEP: 
            # PAL_STOMACH_DECREASE_RATE: 
            # PAL_STAMINA_DECREASE_RATE: 
            # PAL_AUTO_HP_REGEN_RATE: 
            # PAL_AUTO_HP_REGEN_RATE_IN_SLEEP: 
            # BUILD_OBJECT_DAMAGE_RATE: 
            # BUILD_OBJECT_DETERIORATION_DAMAGE_RATE: 
            # COLLECTION_DROP_RATE: 
            # COLLECTION_OBJECT_HP_RATE: 
            # COLLECTION_OBJECT_RESPAWN_SPEED_RATE: 
            # ENEMY_DROP_ITEM_RATE: 
            DEATH_PENALTY: Item
            # ENABLE_PLAYER_TO_PLAYER_DAMAGE: 
            # ENABLE_FRIENDLY_FIRE: 
            # ENABLE_INVADER_ENEMY: 
            # ACTIVE_UNKO: 
            # ENABLE_AIM_ASSIST_PAD: 
            ENABLE_AIM_ASSIST_KEYBOARD: True
            # DROP_ITEM_MAX_NUM: 
            # DROP_ITEM_MAX_NUM_UNKO: 
            # BASE_CAMP_MAX_NUM: 
            # BASE_CAMP_WORKER_MAXNUM: 
            # DROP_ITEM_ALIVE_MAX_HOURS: 
            # AUTO_RESET_GUILD_NO_ONLINE_PLAYERS: 
            # AUTO_RESET_GUILD_TIME_NO_ONLINE_PLAYERS: 
            # GUILD_PLAYER_MAX_NUM: 
            PAL_EGG_DEFAULT_HATCHING_TIME: 1
            # WORK_SPEED_RATE: 
            # IS_MULTIPLAY: 
            # IS_PVP: 
            # CAN_PICKUP_OTHER_GUILD_DEATH_PENALTY_DROP: 
            # ENABLE_NON_LOGIN_PENALTY: 
            # ENABLE_FAST_TRAVEL: 
            # IS_START_LOCATION_SELECT_BY_MAP: 
            # EXIST_PLAYER_AFTER_LOGOUT: 
            # ENABLE_DEFENSE_OTHER_GUILD_PLAYER: 
            # COOP_PLAYER_MAX_NUM: 
            # REGION: 
            # USEAUTH: 
            # BAN_LIST_URL: 
            ENABLE_RCON: true
            RCON_PORT: 25575
          envFrom:
            - secretRef:
                name: discord-webhook-secret

          resources:
            limits:
              memory: 8Gi
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
        backup:
          dependsOn: main
          image:
            repository: registry.hub.docker.com/instrumentisto/rsync-ssh
            tag: alpine3.19
          command:
            - "/bin/sh"
            - "-c"
            - |
              while true; do
                current_time=$(date +"%H:%M")
                if [ "$current_time" == "06:00" ]; then
                  rsync -e "ssh -o StrictHostKeyChecking=no -i /palworld/ssh_key" -avz /palworld root@192.168.0.30:/mnt/palworld/$(date +"%F")
                  echo "rsync command executed at 6 am"
                  sleep $((24 * 60 * 60))  # Sleep for 24 hours (next day)
                else
                  sleep 60
                fi
              done

  service:
    main:
      controller: main
      ports:
        http:
          port: 8211
          protocol: UDP
        rcon:
          port: 25575
          protocol: UDP
        query:
          port: 27015
          protocol: UDP
      type: LoadBalancer
      loadBalancerIP: 192.168.0.69
  persistence:
    palworld:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 30Gi
      storageClass: local-path-ssd
      globalMounts:
        - path: /palworld
