app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: registry.hub.docker.com/jammsen/palworld-dedicated-server
            tag: latest
          env:
            ALWAYS_UPDATE_ON_START: true
            MAX_PLAYERS: 32
            MULTITHREAD_ENABLED: true
            COMMUNITY_SERVER: false
            RCON_ENABLED: true
            RCON_PORT: 25575
            PUBLIC_PORT: 8211
            SERVER_NAME: bambi-palworld
            SERVER_DESCRIPTION: Palworld-Dedicated-Server running in Docker by Bambi
            SERVER_PASSWORD: bambi4ever
            ADMIN_PASSWORD: bambi4ever 
        probes:
          liveness:
            enabled: false
          readiness:
            enabled: false
          startup:
            enabled: false
  service:
    main:
      type: LoadBalancer
      externalTrafficPolicy: Cluster
      loadBalancerIP: 192.168.0.69
      annotations:
        metallb.universe.tf/allow-shared-ip: palworld
      ports:
        http:
          enabled: false
          primary: false
        game:
          enabled: true
          port: 8211
          protocol: UDP
  persistence:
    palworld:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 30Gi
      mountpath: /palworld
      storageClass: local-path-ssd
