app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: registry.hub.docker.com/_/eclipse-mosquitto
            tag: 2.0.21
  service:
    main:
      controller: main
      ports:
        mqtt:
          port: 1883
          targetPort: 1883
        mqtt-websocket:
          port: 9001
          targetPort: 9001
  persistence:
    data:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 1Gi
      storageClass: local-path-ssd
      globalMounts:
        - path: /data
    config:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 1Gi
      storageClass: local-path-ssd
      globalMounts:
        - path: /config
