app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: eclipse-mosquitto
            tag: 2.0.22
  service:
    main:
      controller: main
      ports:
        http:
          port: 1883
          targetPort: 1883
        mqtt-websocket:
          port: 9001
          targetPort: 9001
  persistence:
    data:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 1Gi
      storageClass: local-path-ssd
      globalMounts:
        - path: /data
      forceRename: mosquitto-data
    config:
      enabled: true
      type: configMap
      name: mosquitto-config
      globalMounts:
        - path: /mosquitto/config/mosquitto.conf
          subPath: mosquitto.conf
