app-template:

  image:
    repository: registry.hub.docker.com/fallenbagel/jellyseerr
    tag: 1.4.1

  service:
    main:
      ports:
        http:
          port: &port 5055

  ingress:
    main:
      enabled: true
      annotations:
        nginx.org/websocket-services: "jellyseerr"
        cert-manager.io/cluster-issuer: "issuer"
      hosts:
        - host: &host requests.intropin.be
          paths:
            - path: /
              pathType: Prefix
              service:
                port: 8096
      tls:
        - secretName: requests-letsencrypt-certificate
          hosts: [*host]

  podSecurityContext:
    runAsUser: 568
    runAsGroup: 568
    fsGroup: 568
    fsGroupChangePolicy: "Always"

  persistence:
    config:
      enabled: true
      type: pvc
      accessMode: ReadWriteOnce
      size: 1Gi
      mountpath: /app/config
      storageClass: local-path-ssd
