traefik:
  # Enable Traefik ingress controller
  deployment:
    enabled: true

  # Service exposure - use LoadBalancer or NodePort depending on your setup
  service:
    enabled: true
    type: LoadBalancer
    ports:
      web:
        port: 80
      websecure:
        port: 443

  # Enable ingressRoute CRDs
  ingressRoute:
    dashboard:
      enabled: false
 
  # Entrypoints for HTTP and HTTPS
  entryPoints:
    web:
      address: ":80"
      http:
        redirections:
          entryPoint:
            to: websecure
            scheme: https
    websecure:
      address: ":443"
      http:
        tls:
          certResolver: letsencrypt

  # Use Let's Encrypt with cert-manager (preferred in homelab)
  certResolvers:
    letsencrypt:
      acme:
        email: "jan.peters1995@gmail.com"        
        storage: /data/acme.json
        httpChallenge:
          entryPoint: web

  # Enable logging
  logs:
    general:
      level: INFO
    access:
      enabled: true
      format: json

  # Enable metrics (optional)
  metrics:
    prometheus:
      enabled: true

  # Enable providers
  providers:
    kubernetesCRD:
      enabled: true
    kubernetesIngress:
      enabled: true
    file:
      enabled: false

  # Traefik dashboard service
  dashboard:
    enabled: true
    domain: "traefik.intropin.be"  # replace with your subdomain

  # Persistence for ACME data
  persistence:
    enabled: true
    name: data
    accessMode: ReadWriteOnce
    size: 128Mi
    path: /data

  # SecurityContext to avoid root
  securityContext:
    capabilities:
      drop: ["ALL"]
      add: ["NET_BIND_SERVICE"]
    runAsNonRoot: true
    runAsUser: 65532
