traefik:
  # Global configuration
  globalArguments:
    - "--global.checknewversion=false"
    - "--global.sendanonymoususage=false"

  # Deployment configuration
  deployment:
    replicas: 1
    podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/path: "/metrics"
      prometheus.io/port: "8080"

  # Service configuration
  service:
    enabled: true
    type: LoadBalancer
    # Use MetalLB IP range
    loadBalancerIP: 192.168.0.60
    annotations:
      metallb.universe.tf/allow-shared-ip: traefik
    spec:
      externalTrafficPolicy: Local

  # Ports configuration
  ports:
    web:
      port: 80
      expose: true
      exposedPort: 80
      protocol: TCP
    websecure:
      port: 443
      expose: true
      exposedPort: 443
      protocol: TCP
      tls:
        enabled: true
    traefik:
      port: 8080
      expose: false
      protocol: TCP

  # Ingress configuration
  ingressRoute:
    dashboard:
      enabled: false

  # Provider configuration
  providers:
    kubernetesCRD:
      enabled: true
      allowCrossNamespace: true
      allowExternalNameServices: true
    kubernetesIngress:
      enabled: true
      allowExternalNameServices: true
      publishedService:
        enabled: true

  # No certificate resolvers needed - cert-manager handles certificates

  # Security context
  securityContext:
    capabilities:
      drop: [ALL]
    readOnlyRootFilesystem: true
    runAsGroup: 65532
    runAsNonRoot: true
    runAsUser: 65532

  podSecurityContext:
    fsGroup: 65532

  # Resource limits
  resources:
    requests:
      cpu: 100m
      memory: 50Mi
    limits:
      cpu: 300m
      memory: 150Mi

  # Node selector for specific nodes if needed
  nodeSelector: {}

  # Tolerations
  tolerations: []

  # Affinity
  affinity: {}

  # Priority class
  priorityClassName: system-cluster-critical

  # Additional arguments
  additionalArguments:
    - "--serversTransport.insecureSkipVerify=true"
    - "--log.level=INFO"
    - "--accesslog=true"
    - "--metrics.prometheus=true"
    - "--metrics.prometheus.addEntryPointsLabels=true"
    - "--metrics.prometheus.addServicesLabels=true"
    - "--entrypoints.web.address=:80"
    - "--entrypoints.websecure.address=:443"
    - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
    - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
