traefik: 
  deployment:
    enabled: true

  service:
    enabled: true
    type: LoadBalancer
    ports:
      web:
        port: 80
      websecure:
        port: 443

  ingressRoute:
    dashboard:
      enabled: false  # ensure dashboard is disabled

  entryPoints:
    web:
      address: ":80"
      http:
        redirections:
          entryPoint:
            to: websecure
            scheme: https
    websecure:
      address: ":443"
      http:
        tls:
          certResolver: letsencrypt

  certResolvers:
    letsencrypt:
      acme:
        email: "jan.peters1995@gmail.com"
        storage: "/data/acme.json"
        httpChallenge:
          entryPoint: web

  logs:
    general:
      level: INFO
    access:
      enabled: true
      format: json

  providers:
    kubernetesCRD:
      enabled: true
    kubernetesIngress:
      enabled: true

  persistence:
    enabled: true
    name: data
    accessMode: ReadWriteOnce
    size: 128Mi
    path: /data

  securityContext:
    capabilities:
      drop: ["ALL"]
      add: ["NET_BIND_SERVICE"]
    runAsNonRoot: true
    runAsUser: 65532
