traefik:
  deployment:
    enabled: true

  service:
    enabled: true
    type: LoadBalancer  # Change to NodePort if needed
    ports:
      web:
        port: 80
      websecure:
        port: 443

  ingressRoute:
    dashboard:
      enabled: false

  entryPoints:
    web:
      address: ":80"
      http:
        redirections:
          entryPoint:
            to: websecure
            scheme: https
    websecure:
      address: ":443"
      http:
        tls:
          enabled: true  # Required for cert-manager to bind TLS routes

  # Logging
  logs:
    general:
      level: INFO
    access:
      enabled: true
      format: json

  # Providers: Ingress + CRDs
  providers:
    kubernetesCRD:
      enabled: true
    kubernetesIngress:
      enabled: true

  # Persistence (optional, can be removed if not used)
  persistence:
    enabled: false

  # Security best practices
  securityContext:
    capabilities:
      drop: ["ALL"]
      add: ["NET_BIND_SERVICE"]
    runAsNonRoot: true
    runAsUser: 65532
