traefik:
  # Global configuration
  globalArguments:
    - "--global.checknewversion=false"
    - "--global.sendanonymoususage=false"

  # Deployment configuration
  deployment:
    replicas: 1
    podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/path: "/metrics"
      prometheus.io/port: "8080"

  # Service configuration
  service:
    enabled: true
    type: LoadBalancer
    # Use MetalLB IP range
    loadBalancerIP: 192.168.0.60
    annotations:
      metallb.universe.tf/allow-shared-ip: traefik
    spec:
      externalTrafficPolicy: Local

  # Ports configuration
  ports:
    web:
      port: 80
      expose:
        default: true
      exposedPort: 80
      protocol: TCP
    websecure:
      port: 443
      expose:
        default: true
      exposedPort: 443
      protocol: TCP
      tls:
        enabled: true


  # Ingress configuration
  ingressRoute:
    dashboard:
      enabled: false

  # Provider configuration
  providers:
    kubernetesCRD:
      enabled: true
      allowCrossNamespace: true
      allowExternalNameServices: true
    kubernetesIngress:
      enabled: true
      allowExternalNameServices: true
      publishedService:
        enabled: true


  # Resource limits
  resources:
    requests:
      cpu: 100m
      memory: 50Mi
    limits:
      cpu: 300m
      memory: 150Mi

  # Node selector for specific nodes if needed
  nodeSelector: {}

  # Tolerations
  tolerations: []

  # Affinity
  affinity: {}

  # Priority class
  priorityClassName: system-cluster-critical

  # Additional arguments
  additionalArguments:
    - "--serversTransport.insecureSkipVerify=true"
    - "--log.level=INFO"
    - "--accesslog=true"

