local-path-provisioner-ssd:
  storageClass:
    create: false
    name: local-path-ssd
  configmap:
    name: local-path-config-ssd
  nodePathMap:
    - node: DEFAULT_PATH_FOR_NON_LISTED_NODES
      paths:
        - /var/mnt/ssd/
