---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: home-assistant-external-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "issuer"
spec:
  rules:
  - host: ha.intropin.be
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: home-assistant-service
            port:
              number: 8123
  tls:
  - hosts:
    - ha.intropin.be
    secretName: home-assistant-tls-secret
---
apiVersion: v1
kind: Service
metadata:
  name: home-assistant-service
spec:
  clusterIP: None  # This makes it a headless service
  ports:
  - port: 8123
    targetPort: 8123
  selector: {}
  externalIPs:
  - 192.168.0.146
