---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: home-assistant-external-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "issuer"
spec:
  rules:
  - host: ha.intropin.be 
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: home-assistant-service
            port:
              number: 80
  tls:
  - hosts:
    - ha.intropin.be
    secretName: home-assistant-tls-secret
---
apiVersion: v1
kind: Service
metadata:
  name: home-assistant-service
spec:
  type: ExternalName
  externalName: 192.168.0.146
  ports:
  - port: 80
    targetPort: 8123
