---
apiVersion: v2
name: grafana
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
- name: grafana-k8s-monitoring grafana/k8s-monitoring
  version: 3.5.1
  repository: https://grafana.github.io/helm-charts
