k8s-monitoring
  cluster:
    name: echel
  destinations:
    - name: metricsService
      type: prometheus
      url: https://prometheus-prod-24-prod-eu-west-2.grafana.net/api/prom/push
      auth:
        type: basic
        username: '1934772'
        password: >-
          glc_eyJvIjoiMTI4ODk1NCIsIm4iOiJzdGFjay0xMTA4ODg0LWludGVncmF0aW9uLWt1YmUtZWNodGVsLWt1YmUtZWNodGVsIiwiayI6ImU1NnNOODE4bURYUjYxdm0zYVNMOU1jMyIsIm0iOnsiciI6InByb2QtZXUtd2VzdC0yIn19
    - name: logsService
      type: loki
      url: https://logs-prod-012.grafana.net/loki/api/v1/push
      auth:
        type: basic
        username: '1066663'
        password: >-
          glc_eyJvIjoiMTI4ODk1NCIsIm4iOiJzdGFjay0xMTA4ODg0LWludGVncmF0aW9uLWt1YmUtZWNodGVsLWt1YmUtZWNodGVsIiwiayI6ImU1NnNOODE4bURYUjYxdm0zYVNMOU1jMyIsIm0iOnsiciI6InByb2QtZXUtd2VzdC0yIn19
    - name: tracesService
      type: otlp
      metrics:
        enabled: false
      logs:
        enabled: false
      traces:
        enabled: true
      url: https://tempo-prod-10-prod-eu-west-2.grafana.net:443
      auth:
        type: basic
        username: '1060978'
        password: >-
          glc_eyJvIjoiMTI4ODk1NCIsIm4iOiJzdGFjay0xMTA4ODg0LWludGVncmF0aW9uLWt1YmUtZWNodGVsLWt1YmUtZWNodGVsIiwiayI6ImU1NnNOODE4bURYUjYxdm0zYVNMOU1jMyIsIm0iOnsiciI6InByb2QtZXUtd2VzdC0yIn19
  clusterMetrics:
    enabled: true
    kube-state-metrics:
      deploy: true
    node-exporter:
      deploy: true
      enabled: true
    opencost:
      enabled: true
      opencost:
        exporter:
          defaultClusterId: echel
        prometheus:
          external:
            url: https://prometheus-prod-24-prod-eu-west-2.grafana.net/api/prom
          existingSecretName: metricsservice-grafana-k8s-monitoring
      metricsSource: metricsService
    kepler:
      enabled: false
  alloy-metrics:
    enabled: true
  clusterEvents:
    enabled: true
  alloy-singleton:
    enabled: true
  podLogs:
    enabled: true
  alloy-logs:
    enabled: true
  applicationObservability:
    enabled: true
    receivers:
      otlp:
        includeDebugMetrics: true
        grpc:
          enabled: true
        http:
          enabled: true
      zipkin:
        enabled: true
        includeDebugMetrics: true
  alloy-receiver:
    enabled: true
  annotationAutodiscovery:
    enabled: true
  prometheusOperatorObjects:
    enabled: true
    crds:
      deploy: true
  integrations:
    alloy:
      instances:
        - name: alloy
          labelSelectors:
            app.kubernetes.io/name:
              - alloy-metrics
              - alloy-singleton
              - alloy-logs
              - alloy-receiver
          metrics:
            tuning:
              useDefaultAllowList: true
              includeMetrics:
                - alloy_build_info
