k8s-monitoring:
  cluster:
    name: cluster01
  destinations:
    - name: grafana-cloud-metrics
      type: prometheus
      url: https://prometheus-prod-24-prod-eu-west-2.grafana.net/api/prom/push
      auth:
        type: basic
        username: "1934772"
        password: glc_eyJvIjoiMTI4ODk1NCIsIm4iOiJzdGFjay0xMTA4ODg0LWludGVncmF0aW9uLWNsdXN0ZXIwMS1jbHVzdGVyMDEiLCJrIjoiMjR0MUhCNzdEd2d0Q2YyMjFFRTA0ZW1XIiwibSI6eyJyIjoicHJvZC1ldS13ZXN0LTIifX0=
    - name: grafana-cloud-logs
      type: loki
      url: https://logs-prod-012.grafana.net/loki/api/v1/push
      auth:
        type: basic
        username: "1066663"
        password: glc_eyJvIjoiMTI4ODk1NCIsIm4iOiJzdGFjay0xMTA4ODg0LWludGVncmF0aW9uLWNsdXN0ZXIwMS1jbHVzdGVyMDEiLCJrIjoiMjR0MUhCNzdEd2d0Q2YyMjFFRTA0ZW1XIiwibSI6eyJyIjoicHJvZC1ldS13ZXN0LTIifX0=
    - name: grafana-cloud-traces
      type: otlp
      url: https://tempo-prod-10-prod-eu-west-2.grafana.net:443
      protocol: grpc
      auth:
        type: basic
        username: "1060978"
        password: glc_eyJvIjoiMTI4ODk1NCIsIm4iOiJzdGFjay0xMTA4ODg0LWludGVncmF0aW9uLWNsdXN0ZXIwMS1jbHVzdGVyMDEiLCJrIjoiMjR0MUhCNzdEd2d0Q2YyMjFFRTA0ZW1XIiwibSI6eyJyIjoicHJvZC1ldS13ZXN0LTIifX0=
      metrics:
        enabled: false
      logs:
        enabled: false
      traces:
        enabled: true
  clusterMetrics:
    enabled: true
    opencost:
      enabled: true
      metricsSource: grafana-cloud-metrics
      opencost:
        exporter:
          defaultClusterId: cluster01
        prometheus:
          existingSecretName: grafana-cloud-metrics-grafana-k8s-monitoring
          external:
            url: https://prometheus-prod-24-prod-eu-west-2.grafana.net/api/prom
    kepler:
      enabled: true
  clusterEvents:
    enabled: true
  podLogs:
    enabled: true
  applicationObservability:
    enabled: true
    receivers:
      otlp:
        grpc:
          enabled: true
          port: 4317
        http:
          enabled: true
          port: 4318
      zipkin:
        enabled: true
        port: 9411
  alloy-metrics:
    enabled: true
    alloy:
      extraEnv:
        - name: GCLOUD_RW_API_KEY
          valueFrom:
            secretKeyRef:
              name: alloy-metrics-remote-cfg-grafana-k8s-monitoring
              key: password
        - name: CLUSTER_NAME
          value: cluster01
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: GCLOUD_FM_COLLECTOR_ID
          value: grafana-k8s-monitoring-$(CLUSTER_NAME)-$(NAMESPACE)-$(POD_NAME)
    remoteConfig:
      enabled: true
      url: https://fleet-management-prod-011.grafana.net
      auth:
        type: basic
        username: "1108884"
        password: glc_eyJvIjoiMTI4ODk1NCIsIm4iOiJzdGFjay0xMTA4ODg0LWludGVncmF0aW9uLWNsdXN0ZXIwMS1jbHVzdGVyMDEiLCJrIjoiMjR0MUhCNzdEd2d0Q2YyMjFFRTA0ZW1XIiwibSI6eyJyIjoicHJvZC1ldS13ZXN0LTIifX0=
  alloy-singleton:
    enabled: true
    alloy:
      extraEnv:
        - name: GCLOUD_RW_API_KEY
          valueFrom:
            secretKeyRef:
              name: alloy-singleton-remote-cfg-grafana-k8s-monitoring
              key: password
        - name: CLUSTER_NAME
          value: cluster01
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: GCLOUD_FM_COLLECTOR_ID
          value: grafana-k8s-monitoring-$(CLUSTER_NAME)-$(NAMESPACE)-$(POD_NAME)
    remoteConfig:
      enabled: true
      url: https://fleet-management-prod-011.grafana.net
      auth:
        type: basic
        username: "1108884"
        password: glc_eyJvIjoiMTI4ODk1NCIsIm4iOiJzdGFjay0xMTA4ODg0LWludGVncmF0aW9uLWNsdXN0ZXIwMS1jbHVzdGVyMDEiLCJrIjoiMjR0MUhCNzdEd2d0Q2YyMjFFRTA0ZW1XIiwibSI6eyJyIjoicHJvZC1ldS13ZXN0LTIifX0=
  alloy-logs:
    enabled: true
    alloy:
      extraEnv:
        - name: GCLOUD_RW_API_KEY
          valueFrom:
            secretKeyRef:
              name: alloy-logs-remote-cfg-grafana-k8s-monitoring
              key: password
        - name: CLUSTER_NAME
          value: cluster01
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: GCLOUD_FM_COLLECTOR_ID
          value: grafana-k8s-monitoring-$(CLUSTER_NAME)-$(NAMESPACE)-alloy-logs-$(NODE_NAME)
    remoteConfig:
      enabled: true
      url: https://fleet-management-prod-011.grafana.net
      auth:
        type: basic
        username: "1108884"
        password: glc_eyJvIjoiMTI4ODk1NCIsIm4iOiJzdGFjay0xMTA4ODg0LWludGVncmF0aW9uLWNsdXN0ZXIwMS1jbHVzdGVyMDEiLCJrIjoiMjR0MUhCNzdEd2d0Q2YyMjFFRTA0ZW1XIiwibSI6eyJyIjoicHJvZC1ldS13ZXN0LTIifX0=
  alloy-receiver:
    enabled: true
    alloy:
      extraPorts:
        - name: otlp-grpc
          port: 4317
          targetPort: 4317
          protocol: TCP
        - name: otlp-http
          port: 4318
          targetPort: 4318
          protocol: TCP
        - name: zipkin
          port: 9411
          targetPort: 9411
          protocol: TCP
      extraEnv:
        - name: GCLOUD_RW_API_KEY
          valueFrom:
            secretKeyRef:
              name: alloy-receiver-remote-cfg-grafana-k8s-monitoring
              key: password
        - name: CLUSTER_NAME
          value: cluster01
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: GCLOUD_FM_COLLECTOR_ID
          value: grafana-k8s-monitoring-$(CLUSTER_NAME)-$(NAMESPACE)-alloy-receiver-$(NODE_NAME)
    remoteConfig:
      enabled: true
      url: https://fleet-management-prod-011.grafana.net
      auth:
        type: basic
        username: "1108884"
        password: glc_eyJvIjoiMTI4ODk1NCIsIm4iOiJzdGFjay0xMTA4ODg0LWludGVncmF0aW9uLWNsdXN0ZXIwMS1jbHVzdGVyMDEiLCJrIjoiMjR0MUhCNzdEd2d0Q2YyMjFFRTA0ZW1XIiwibSI6eyJyIjoicHJvZC1ldS13ZXN0LTIifX0=
  EOF
