app-template:
 image:
   repository: wolveix/satisfactory-server
   tag: v1.4.8
 env:
   DATA_FOLDER: "config"
   AUTOSAVENUM: 25
   AUTOPAUSE: true
 service:
   main:
     type: LoadBalancer
     externalTrafficPolicy: Cluster
     loadBalancerIP: 192.168.0.39
     annotations:
       metallb.universe.tf/allow-shared-ip: satisfactory
     ports:
       http:
         enabled: false
         primary: false
       query:
         enabled: true
         port: 15777
         protocol: UDP
       beacon:
         enabled: true
         port: 15000
         protocol: UDP
       game:
         enabled: true
         port: 7777
         protocol: UDP
 persistence:
   config:
    enabled: true
    type: pvc
    accessMode: ReadWriteOnce
    size: 5G
    mountpath: /config
    storageClass: local-path-ssd
   server-cache:
     enabled: true
     type: pvc
     accessMode: ReadWriteOnce
     size: 10G
     mountPath: /config/gamefiles
     storageClass: local-path-ssd
 probes:
   startup:
     enabled: false
   liveness:
     enabled: false
   readiness:
     enabled: false
