---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library
  labels:
    app: immich-library
spec:
  storageClassName: default
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

