---
n8n:
  service:
    main:
      ports:
        http:
          port: 5678

  config:
    database:
      type: postgresdb
      postgresdb:
        host: n8n-database-rw.apps.svc.cluster.local

  extraEnv:
    N8N_LOG_LEVEL: debug
    WEBHOOK_TUNNEL_URL: "https://n8n.intropin.be"

  extraEnvSecret:
    DB_POSTGRES_USER:
      name: n8n-database-app
      key: username
    DB_POSTGRES_PASSWORD:
      name: n8n-database-app
      key: password

  ingress:
    main:
      enabled: true
      annotations:
        nginx.org/websocket-services: "n8n"
        cert-manager.io/cluster-issuer: "issuer"
      hosts:
        - host: &host n8n.intropin.be
          paths:
            - path: /
              pathType: Prefix
              service:
                port: 5678
      tls:
        - secretName: n8n-letsencrypt-certificate
          hosts: [*host]
  persistence:
    config:
      enabled: true
      type: pvc 
      accessMode: ReadWriteOnce
      size: 1Gi
      mountPath: /home/node/.n8n
      storageClass: local-path-ssd
