---
version: "3"

dotenv:
  - './.env'

tasks:
  full_install:
    desc: Do all tasks required to do a clean bootstrap
    dir: ./
    cmds:
      - task: hypervisor_init
      - task: terraform_vm_init
      - task: talos_init
      - task: argocd_init

  hypervisor_init:
    desc: Setup proxmox hypervisor_init
    dir: ./infra/ansible/
    cmds:
      - ansible-playbook setup-hypervisors.yaml

  terraform_vm_init:
    desc: Configure and start up required VMs
    dir: ./infra/terraform/
    cmds:
      - terraform init
      - terraform apply -auto-approve
      - ssh root@$HYPERVISOR_IP 'qm set 100 -scsi2 /dev/disk/by-id/$HYPERVISOR_PASSTHROUGH_DISK_SSD -scsi3 /dev/disk/by-id/$HYPERVISOR_PASSTHROUGH_DISK_HDD'

  terraform_vm_destroy:
    desc: Delete VMs
    dir: ./infra/terraform/
    cmds:
      - ssh root@$HYPERVISOR_IP 'qm unlink 100 --idlist scsi2 --idlist scsi3'
      - terraform destroy -auto-approve

  talos_init:
    desc: Configure talos on the VM
    dir: ./infra/talos/
    cmds:
      - talhelper genconfig
      - talosctl apply-config --insecure --file clusterconfig/echel-master-01.yaml --nodes $(cat ../terraform/script_get_vm_ips/output.txt | jq -r '.[]')
      - echo "Sleeping to let talos get installed" && sleep 180 
      - talosctl --talosconfig clusterconfig/talosconfig config endpoint $TALOS_NODE_IP
      - talosctl --talosconfig clusterconfig/talosconfig config node $TALOS_NODE_IP
      - talosctl --talosconfig clusterconfig/talosconfig bootstrap 
      - echo "Sleeping to let talos get bootstrapped" ; sleep 120
      - talosctl --talosconfig clusterconfig/talosconfig kubeconfig ~/.kube/config

  argocd_init:
    desc: Install ArgoCD using helm
    dir: ./infra/argocd/
    cmds:
      - helm repo add argo https://argoproj.github.io/argo-helm
      - helm upgrade --install argocd argo/argo-cd --create-namespace --namespace argocd --version $ARGOCD_BOOTSTRAP_VERSION --values argocd-values.yaml --wait
      - kubectl apply -f ../../kubernetes/manifests/argocd-seedjobs/manifest-apps.yaml
      - kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d
