metallb:
  controller:
    priorityClassName: system-cluster-critical
  speaker:
    priorityClassName: system-cluster-critical
    # Fix for MicroK8s - speaker needs NET_ADMIN capability for ARP responder
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        add:
          - NET_RAW
          - NET_ADMIN
        drop:
          - ALL
      readOnlyRootFilesystem: true
