metallb:
  controller:
    priorityClassName: system-cluster-critical
  speaker:
    priorityClassName: system-cluster-critical
    # Add missing NET_ADMIN capability for ARP functionality
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        add:
          - NET_RAW
          - NET_ADMIN
        drop:
          - ALL
      readOnlyRootFilesystem: true
