app-template:
    defaultPodOptions:
        securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: "Always"
    controllers:
        main:
            containers:
                main:
                    image:
                        repository: ghcr.io/listenarrs/listenarr
                        tag: canary-0.2.70
    service:
        main:
            controller: main
            ports:
                http:
                    port: 4545
                    targetPort: 4545
    route:
        main:
            enabled: true
            kind: HTTPRoute
            annotations:
                cert-manager.io/cluster-issuer: letsencrypt
            hostnames:
                - listenarr.sunnyvale.be
            parentRefs:
                - name: envoy-gateway
                  namespace: default
                  sectionName: https
    persistence:
        config:
            enabled: true
            type: persistentVolumeClaim
            accessMode: ReadWriteOnce
            size: 1Gi
            storageClass: local-path-ssd
            globalMounts:
                - path: /config
            forceRename: bazarr-config
        downloads:
            enabled: true
            type: persistentVolumeClaim
            accessMode: ReadWriteOnce
            size: 1Gi
            storageClass: local-path-ssd
            globalMounts:
                - path: /downloads
        audiobooks:
            enabled: true
            type: persistentVolumeClaim
            accessMode: ReadWriteOnce
            size: 1Gi
            storageClass: local-path-ssd
            globalMounts:
                - path: /audiobooks
