# Simplified cert-manager configuration that matches the schema
global:
  priorityClassName: system-cluster-critical

# Install CRDs
crds:
  enabled: true
  keep: true

# Resource limits for all components
resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 128Mi

# Replica counts
replicaCount: 1

# Security context (applies to all components)
securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL

# Webhook specific configuration
webhook:
  replicaCount: 1
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 128Mi

# CA Injector specific configuration
cainjector:
  replicaCount: 1
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 128Mi

# Startup API check
startupapicheck:
  enabled: true
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 128Mi

# Prometheus monitoring
prometheus:
  enabled: true
  servicemonitor:
    enabled: false  # Set to true if you have Prometheus operator
