---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-nginx-helm-values
  namespace: core
data:
  values.yaml: |
    controller:
      config:
        client-max-body-size: 8m
        proxy-read-timeout: "300"
        proxy-send-timeout: "300"
        proxy_buffer_size: "128k"
        proxy_buffers: 4 256k
        proxy_busy_buffers_size: 256k

      watchIngressWithoutClass: true
      ingressClassByName: true

      service:
        externalTrafficPolicy: Local
        internal:
          enabled: true
          externalTrafficPolicy: "Local"

      replicaCount: 1

      minAvailable: 1
