authelia:
  domain: intropin.be
  ingress:
    enabled: true
    annotations:
      nginx.org/websocket-services: "outline"
      cert-manager.io/cluster-issuer: "issuer"
      nginx.ingress.kubernetes.io/real-ip-header: "X-Forwarded-For"  # Use X-Forwarded-For header to get the real IP
  pod:
    env:
      - name: TZ
        value: Europe/Brussels
  configMap:
    enabled: true
    theme: dark
    default_redirection_url: https://auth.intropin.be
    totp:
      issuer: authelia.com
    ntp:
      address: be.pool.ntp.org
    authentication_backend:
      ldap.enabled: false
      file:
        enabled: true
        path: /config/users_database.yml
        password:
          algorith: argon2id
          iterations: 1
          salt_length: 16
          parallelism: 8
          memory: 64
    access_control:
      default_policy: one_factor
    session:
      name: authelia_session
      secret: V9eur43qxzzsaJ7q6I7lQ29U4NV4CcdGABKvSJbzjtOeDUbMcUr11yMOJjPvjQz9
      expiration: 1h # 1 hour
      inactivity: 1h # 1 hour
      remember_me_duration: 1M # month
      domain: intropin.be # Should match whatever your root protected domain is
      redis:
        enabled: false
    regulation:
      max_retries: 3
      find_time: 120
      ban_time: 300
    storage:
     encryption_key: 7TTiE99YQfT1bBic6W9Mh5HgbozhoVF8QBX8E9AsbJSA2Jux8obqWKqdH1mOvp32 # Now required
     local:
       path: /config/db.sqlite3
    identity_providers:
      oidc:
        hmac_secret: this_is_a_secret_abc123abc123abc
        issuer_certificate_chain: |
          -----BEGIN CERTIFICATE-----
          MIIDZDCCAkygAwIBAgITcgPkDN+u8/D5Jc9nxPqg5sY5+TANBgkqhkiG9w0BAQsF
          ADBCMQswCQYDVQQGEwJYWDEVMBMGA1UEBwwMRGVmYXVsdCBDaXR5MRwwGgYDVQQK
          DBNEZWZhdWx0IENvbXBhbnkgTHRkMB4XDTIzMTAwNjE0MzcyMFoXDTIzMTEwNTE0
          MzcyMFowQjELMAkGA1UEBhMCWFgxFTATBgNVBAcMDERlZmF1bHQgQ2l0eTEcMBoG
          A1UECgwTRGVmYXVsdCBDb21wYW55IEx0ZDCCASIwDQYJKoZIhvcNAQEBBQADggEP
          ADCCAQoCggEBAKUfdjnADP9jhNh8xt9dUq+iZLH2L9+XSLLahL7ry3A3zByym6Ha
          zcnyy7g6r13BYy/y3Hwx6ns8AxdQCrGNh0/dKiUqpCUNy+dsbftp2LDhQ1OQKAKn
          UZmLedtSRi6hRezhI5XVwm2CABOEpkH3bql7gCEhl2cpnT+w7rmT4igiTzO0F8DF
          Sjp2qWCBqvEGmSE9VwkiJBUxXYI+ii8O5FeuI7Zg6FD2DDoat1nw8Y6fxYAH1wnt
          7MyVa0SZNXkRsSciU8Oi9m3vtLIiX/hZg9+jkKlL8an75Bjf2vXDHApzjcO1Nyq0
          OK5xmgLZ46wcazIWLD+k6sXVOAb1hq6LYUECAwEAAaNTMFEwHQYDVR0OBBYEFIuZ
          gPBtFtlPclN5o5xv0LEXmDg4MB8GA1UdIwQYMBaAFIuZgPBtFtlPclN5o5xv0LEX
          mDg4MA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBAFGdIjR7lG8z
          nixG9qQMBvr+A9dJLUI/r5ox7UQnuK7oWHW/vz4h9NxDU6AT+6KHXJ0CstUYK6hH
          3mN4IYgupBNc9aIPCm23O5wVUOKIHE+EXrSq4WvOhUdjXzD++9qgfBqLQAipVkXO
          tvm0Cj2VDeiq3ZGm4HHZXN3z2SMAEw6heqOFnra+JIBIIltDKmGGuScShQ+/MJE0
          2vG5vv5Ze57GyjokwhtXZBlgcNjCMqS00vABAMY9Q4orcWe8i1P9lQdsqkFPVgUy
          b3dd4JCpqRPHMpI31darY6oJ5kLERqmy4ydoU0mMqdC287QooYnI0UIUwCv0J74P
          h/4D0QvcSug=
          -----END CERTIFICATE-----
        issuer_private_key: |
          -----BEGIN PRIVATE KEY-----
          MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQClH3Y5wAz/Y4TY
          fMbfXVKvomSx9i/fl0iy2oS+68twN8wcspuh2s3J8su4Oq9dwWMv8tx8Mep7PAMX
          UAqxjYdP3SolKqQlDcvnbG37adiw4UNTkCgCp1GZi3nbUkYuoUXs4SOV1cJtggAT
          hKZB926pe4AhIZdnKZ0/sO65k+IoIk8ztBfAxUo6dqlggarxBpkhPVcJIiQVMV2C
          PoovDuRXriO2YOhQ9gw6GrdZ8PGOn8WAB9cJ7ezMlWtEmTV5EbEnIlPDovZt77Sy
          Il/4WYPfo5CpS/Gp++QY39r1wxwKc43DtTcqtDiucZoC2eOsHGsyFiw/pOrF1TgG
          9Yaui2FBAgMBAAECggEAGQ0kZno8yT75J8+1Flc2FRUUpNaTsx7kddS8QKuiZ5SM
          4Cpi0pP7wQXtIrat5hH8cTOt1XPMk29qjU4PSUUOay9D1nQD3OadHFpcIewQPDRO
          KW6HUMZqFVr5R60m86pzuDlR/kiky5tmVTpnROkmqLTmyWAAyd3LkHRQoOa5mtqX
          BafirjxbdSvuNzIMVD9uEz+J0ojy0Q2B1hwUN9sggrjWiRuhOjvyaGHlADPg1p3L
          GSs9yIUjUWyxISMtOsltNGK7bWOjyenSVV31rLr8JD9IXeIMQ7qZ5MB0jWQ3l5rD
          +0H51U+/Ge1RqOjpNHmLf3EFEwnFp3PhpN2F4RfsvwKBgQDiTJOIpz9jaTo8tKSw
          MGLE0p6FKxGJ97yaXAHKyoQNYiIQWHe2hp/JKJDWeHseTiwDdOf9FpwmWW5cAf2x
          ERYBQ3QP7CyF+HGArg+31YwpdlaFU4UQo1iTgNZqqLuZi49VVValfrLwU+rAxVNR
          YdIaPdcPsbBXvjbMxYZXEZrzYwKBgQC6y2zzaFn0bImQ49147Fs2xLLH12BhE5Cs
          0+z7pJEUBtycSrHpMx6GNW06p4PZCDrUaA3v1Uh3q57FD6nAEDhHbMyLUkDpHPra
          EmOsbBiTrhLaSn5Di3IF4Rx88UJpQVEDUYDtIrtY0IG355sA0B0Ld5HR1sbTQS8w
          ScbCPYMkCwKBgQCW9iyJQcDYiU7vRjaCzpRk5ngXMAbwOdKYSn5rkLOM1gURUGLz
          4VTgdW5BlHfVXKKh37AOtrGOJ6SmPjHFmDdMunnHUW7WJElbZUJZCV0KH8ZSBMhE
          tCMXqx/eYRdcs6v3agl2N1IZXnHBDSGqrY3iMZSxBIE1109pRO98T+NFLwKBgQCm
          pAhEddmaRqHLEp1n3WPaTkw4IBopQG0W4dFPBZcvyJdTDwf8xM/8ZvlVFFB5c/AX
          weR9C0clC4QOxVRotY+fmJ45xF2IGYRou3MURTL/vJGxEDfoRiSovhTOGeVnRQ/i
          5/kelJeSOiEfUY1kgkUHD9qU2whxOnvAlnCspHez1QKBgQDU9/7XPatanD9yXbla
          5DLYQmSunzROhNv+Bod7JLZq7+F70p8Ijv9uDTRz1XXPNe6Dlq5lDP9VwzG89Dzf
          8i3S9bwMU8M4Xputs4njPSVmXMvJOcvbpt8G2tiMs9D9Kcx1CPhk9W6Tcm8hyizS
          Y74s6HLc42UoVF/xRnyC8ZxVdQ==
          -----END PRIVATE KEY-----
        access_token_lifespan: 1h
        authorize_code_lifespan: 1m
        id_token_lifespan: 1h
        refresh_token_lifespan: 90m
        enable_client_debug_messages: true
        enforce_pkce: public_clients_only
        cors:
          endpoints:
            - authorization
            - token
            - revocation
            - introspection
          allowed_origins:
            - https://intropin.be
          allowed_origins_from_client_redirect_uris: false
        clients:
        - id: outline
          description: Outline
          secret: '$pbkdf2-sha512$310000$c8p78n7pUMln0jzvd4aK4Q$JNRBzwAo0ek5qKn50cFzzvE9RXV88h1wJn5KGiHrD0YKtZaR/nCb2CJPOsKaPK0hjf.9yHxzQGZziziccp6Yng'  # The digest of 'insecure_secret'.
          public: false
          authorization_policy: one_factor
          redirect_uris:
            - https://outline.intropin.be/auth/oidc.callback
          scopes:
            - openid
            - offline_access
            - profile
            - email
          userinfo_signing_algorithm: none
