authelia:
  config:
    storage:
      local:
        path: /config/db.sqlite3

    authentication_backend:
      file:
        path: /config/users.yml

    access_control:
      default_policy: deny
      rules:
        - domain: "*.intropin.be"
          policy: one_factor

    session:
      name: authelia_session
      secret: your-session-secret
      expiration: 3600
      domain: intropin.be

    regulation:
      max_retries: 3
      find_time: 120
      ban_time: 300

    jwt_secret: your-jwt-secret

    oidc:
      clients:
        - id: argocd
          description: ArgoCD
          secret: your-argocd-client-secret
          redirect_uris:
            - https://argocd.intropin.be/auth/callback
          scopes:
            - openid
            - profile
            - email
          grant_types:
            - authorization_code
          response_types:
            - code
          token_endpoint_auth_method: client_secret_post

    server:
      host: 0.0.0.0
      port: 9091

    tls:
      key: /config/ssl/key.pem
      certificate: /config/ssl/cert.pem

    logging:
      level: info
      format: text

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: "issuer"
    nginx.ingress.kubernetes.io/real-ip-header: "X-Forwarded-For"
  hosts:
    - host: auth.intropin.be
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - auth.intropin.be
      secretName: authelia-tls

# User file for basic authentication backend
extraConfigFiles:
  users.yml: |
    users:
      jan:
        disabled: false
        displayname: "Jan Peters"
        password: "$argon2id$v=19$m=65536,t=3,p=4$WmNI29/6AWArBdLdgdEZgA$wB0Uoy9K9KYZ/MR6uQ12k93RVj7h8fKKjdNv+0xN2aY"
        email: jan.peters1995@gmail.com
        groups:
          - admin
