authelia:
  domain: intropin.be
  ingress:
    main:
      enabled: true
      annotations:
        nginx.org/websocket-services: "authelia"
        cert-manager.io/cluster-issuer: "issuer"
      hosts:
        - host: &host authelia.intropin.be
          paths:
            - path: /
              pathType: Prefix
              service:
                port: 8123
      tls:
        - secretName: authelia-letsencrypt-certificate
          hosts: [*host]
  configMap:
    enabled: false
    existingConfigMap: authelia-cm
    key: configuration.yaml
