authelia:
  domain: intropin.be
  ingress:
    enabled: true
    annotations:
      nginx.org/websocket-services: "outline"
      cert-manager.io/cluster-issuer: "issuer"
      nginx.ingress.kubernetes.io/real-ip-header: "X-Forwarded-For"  # Use X-Forwarded-For header to get the real IP
  pod:
    env:
      - name: TZ
        value: Europe/Brussels
    extraVolumeMounts:
      - mountPath: /config/users_database.yml
        name: authelia-userdb
        readOnly: true
        subPath: users_database.yaml
    extraVolumes:
      - name: authelia-userdb
        configMap:
          name: authelia-userdb
          items:
            - key: users_database.yaml
              path: users_database.yaml
  configMap:
    enabled: true
    theme: dark
    default_redirection_url: https://auth.intropin.be
    totp:
      issuer: authelia.com
    ntp:
      address: be.pool.ntp.org
    authentication_backend:
      ldap:
        enabled: false
      file:
        enabled: true
        path: /config/users_database.yml
        password:
          algorith: argon2id
          iterations: 1
          salt_length: 16
          parallelism: 8
          memory: 64
    access_control:
      default_policy: one_factor
      rules:
        - domain: outline.intropin.be
          subject:
            group: users
    session:
      name: authelia_session
      secret: V9eur43qxzzsaJ7q6I7lQ29U4NV4CcdGABKvSJbzjtOeDUbMcUr11yMOJjPvjQz9
      expiration: 1h # 1 hour
      inactivity: 1h # 1 hour
      remember_me_duration: 1M # month
      domain: intropin.be # Should match whatever your root protected domain is
      redis:
        enabled: false
    regulation:
      max_retries: 3
      find_time: 120
      ban_time: 300
    storage:
      encryption_key: 7TTiE99YQfT1bBic6W9Mh5HgbozhoVF8QBX8E9AsbJSA2Jux8obqWKqdH1mOvp32 # Now required
      local:
        enabled: true
        path: /config/db.sqlite3
      postgres:
        enabled: false
      mysql:
        enabled: false
    identity_providers:
      oidc:
        enabled: true
        hmac_secret: this_is_a_secret_abc123abc123abc
        access_token_lifespan: 1h
        authorize_code_lifespan: 1m
        id_token_lifespan: 1h
        refresh_token_lifespan: 90m
        enable_client_debug_messages: true
        enforce_pkce: public_clients_only
        cors:
          endpoints:
            - authorization
            - token
            - revocation
            - introspection
          allowed_origins:
            - https://intropin.be
          allowed_origins_from_client_redirect_uris: false
        clients:
        - id: outline
          description: Outline
          secret: '$pbkdf2-sha512$310000$c8p78n7pUMln0jzvd4aK4Q$JNRBzwAo0ek5qKn50cFzzvE9RXV88h1wJn5KGiHrD0YKtZaR/nCb2CJPOsKaPK0hjf.9yHxzQGZziziccp6Yng'  # The digest of 'insecure_secret'.
          public: false
          authorization_policy: one_factor
          redirect_uris:
            - https://outline.intropin.be/auth/oidc.callback
          scopes:
            - openid
            - offline_access
            - profile
            - email
          userinfo_signing_algorithm: none
    notifier:
      filesystem:
        enabled: true
        filename: /config/notification.txt
      smtp:
        enabled: false
