app-template:
  image:
    repository: ghcr.io/authelia/authelia
    tag: v4.38.0-beta2
  args: ["--config", "/config/configuration.yaml", "--config.experimental.filters", "expand-env"]
  env:
    AUTHELIA_DEFAULT_REDIRECTION_URL: https://auth.intropin.be
    AUTHELIA_DUO_API_DISABLE: "true"
    AUTHELIA_LOG_LEVEL: info
    AUTHELIA_SERVER_DISABLE_HEALTHCHECK: "true"
    AUTHELIA_SERVER_PORT: 80
    AUTHELIA_SESSION_DOMAIN: intropin.be
    AUTHELIA_THEME: grey
    AUTHELIA_TOTP_ISSUER: authelia.com
    AUTHELIA_WEBAUTHN_DISABLE: "true"
  enableServiceLinks: false
  service:
    main:
      ports:
        http:
          port: 8080

  ingress:
    main:
      enabled: true
      annotations:
        nginx.org/websocket-services: "home-assistant"
        cert-manager.io/cluster-issuer: "issuer"
        nginx.ingress.kubernetes.io/configuration-snippet: |
          add_header Cache-Control "no-store";
          add_header Pragma "no-cache";
          add_header X-Frame-Options "SAMEORIGIN";
          add_header X-XSS-Protection "1; mode=block";
      hosts:
        - host: &host auth.intropin.be
          paths:
            - path: /
              pathType: Prefix
              service:
                port: 8080
      tls:
        - secretName: auth-letsencrypt-certificate
          hosts: [*host]
  persistence:
    config:
      enabled: true
      type: configMap
      name: authelia-cm
      subPath: configuration.yml
      mountPath: /config/configuration.yaml
      readOnly: false
    userdb:
      enabled: true
      type: configMap
      name: authelia-userdb
      subPath: users_database.yaml
      mountPath: /config/users_database.yaml
      readOnly: false
  resources:
    requests:
      cpu: 5m
      memory: 10Mi
    limits:
      memory: 200Mi
  podSecurityContext:
    runAsUser: 568
    runAsGroup: 568
    fsGroup: 568
    fsGroupChangePolicy: OnRootMismatch
