---
authelia:
  ingress:
    enabled: true
    annotations:
        cert-manager.io/cluster-issuer: "issuer"
        nginx.ingress.kubernetes.io/real-ip-header: "X-Forwarded-For"
        nginx.ingress.kubernetes.io/real-ip-header: "X-Forwarded-For"
    certManager: true
    rewriteTarget: true
    tls:
      enabled: true
      secret: 'authelia-tls'

      hostNameOverride: 'auth.intropin.be'

  env:
    - name: 'TZ'
      value: 'Europe/Brussels'

  pod:
    extraVolumes:
      - name: users-database
        configMap: 
          name: authelia-userdb
          items:
          - key: users_database.yml
            path: users_database.yml
      - name: config-dir
        emptyDir: {}
      
    extraVolumeMounts:
      - name: users-database
        mountPath: /config/users_database.yml
        subPath: users_database.yml
        readOnly: true
      - name: config-dir
        mountPath: /config
        subPath: ""

  configMap:
    key: 'configuration.yaml'
    log:
      level: 'debug'
      format: 'text'
  
    theme: 'dark'
  
    identity_validation:
      reset_password:
        jwt_lifespan: '5 minutes'
        jwt_algorithm: 'HS256'
      elevated_session:
        code_lifespan: '5 minutes'
        elevation_lifespan: '10 minutes'
        characters: 8
        require_second_factor: false
        skip_second_factor: false
  
    totp:
      disable: false
  
    ntp:
      address: 'udp://be.pool.ntp.org:123'
  
    authentication_backend:
      password_reset:
        disable: true
      file:
        enabled: true

    notifier:
      filesystem:
        enabled: true
        filename: '/config/notification.txt'

    access_control:
      default_policy: 'deny'
      rules:
        - domain: '*.intropin.be'
          policy: one_factor
          subject: 'group:admin'
  
    session:
      cookies: 
        - subdomain: 'auth'
          domain: 'intropin.be'
  
    storage:
      local:
        enabled: true
        path: /config/db.sqlite3
  
    identity_providers:
      oidc:
        enabled: true
        jwks: []
        clients:
          - client_id: 'argocd'
            client_name: 'Argo CD'
            client_secret:
              value: '$pbkdf2-sha512$310000$c8p78n7pUMln0jzvd4aK4Q$JNRBzwAo0ek5qKn50cFzzvE9RXV88h1wJn5KGiHrD0YKtZaR/nCb2CJPOsKaPK0hjf.9yHxzQGZziziccp6Yng'
              path: /secret/oidc.client.argocd.value
            public: false
            authorization_policy: 'one_factor'
            redirect_uris:
              - https://argocd.intropin.be/auth/callback
            scopes:
              - openid
              - groups
              - email
              - profile
            userinfo_signed_response_alg: 'none'
