authelia:
  domain: intropin.be
  ingress:
    main:
      enabled: true
      annotations:
        nginx.org/websocket-services: "authelia"
        cert-manager.io/cluster-issuer: "issuer"
      hosts:
        - host: &host authelia.intropin.be
          paths:
            - path: /
              pathType: Prefix
              service:
                port: 8123
      tls:
        - secretName: authelia-letsencrypt-certificate
          hosts: [*host]
  configMap:
    enabled: true
    storage:
      mysql.enabled: false
      postgres.enabled: false
      local.enabled: true
    notifier:
      filesystem.enabled: true
      smtp.enabled: true
    sessions:
      redis.enabled: false
