---
authelia:
  ingress:
    enabled: true
    annotations:
        cert-manager.io/cluster-issuer: "issuer"
        nginx.ingress.kubernetes.io/real-ip-header: "X-Forwarded-For"
        nginx.ingress.kubernetes.io/real-ip-header: "X-Forwarded-For"
    certManager: true
    rewriteTarget: true
    tls:
      enabled: true
      secret: 'authelia-tls'

      hostNameOverride: 'auth.intropin.be'

  env:
    - name: 'TZ'
      value: 'Europe/Brussels'

  pod:
    extraVolumes:
      - name: users-database
        configMap: 
          name: authelia-userdb
          items:
          - key: users_database.yml
            path: users_database.yml
      - name: config-dir
        emptyDir: {}
      
    extraVolumeMounts:
      - name: users-database
        mountPath: /config/users_database.yml
        subPath: users_database.yml
        readOnly: true
      - name: config-dir
        mountPath: /config
        subPath: ""

  configMap:
    key: 'configuration.yaml'
    log:
      level: 'debug'
      format: 'text'
  
    theme: 'dark'
  
    identity_validation:
      reset_password:
        jwt_lifespan: '5 minutes'
        jwt_algorithm: 'HS256'
      elevated_session:
        code_lifespan: '5 minutes'
        elevation_lifespan: '10 minutes'
        characters: 8
        require_second_factor: false
        skip_second_factor: false
  
    totp:
      disable: false
  
    ntp:
      address: 'udp://be.pool.ntp.org:123'
  
    authentication_backend:
      password_reset:
        disable: true
      file:
        enabled: true

    notifier:
      filesystem:
        enabled: true
        filename: '/config/notification.txt'

    access_control:
      default_policy: 'deny'
      rules:
        - domain: '*.intropin.be'
          policy: one_factor
          subject: 'group:admin'
  
    session:
      cookies: 
        - subdomain: 'auth'
          domain: 'intropin.be'
  
    storage:
      local:
        enabled: true
        path: /config/db.sqlite3
  
    identity_providers:
      oidc:
        enabled: true

        jwks:
          - key_id: 'key'
            algorithm: 'RS256'
            use: 'sig'
            key:
              value: |
                "-----BEGIN PRIVATE KEY-----\nMIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDNTcbivY7w+Ur6\nosI7+clq78MG1CnWMATFT43G2+93XK6zf9Fqr5S1SDOH6SSZH4TtsnNLp+ITw458\nXEIGGw1Jmqq1WRbK9MiIuih6MMjo/hMqna8JHETIrhgFGYo0YpMpxx1E7FL71R/m\n5TIStmFyJPWMIOiTcTGwmyVMZNtnS7PIQeSx3E3YJLvw+ckYykt3xyl1bR3bfCdp\ndkrVrQJ4tAd4jWvZGEUNY0iVdt9xce2XmgVSZ4jfIUWz6axQaNOewGGFPZnCQpw9\n66S+9haHJOTBycuBrFbrcPuXKNfzgncsSHXinVSJekYk23i5Gzc47BypOrss4wby\n3suCMtZ1AgMBAAECggEBAK2NJyi7x58rjleryPh8Yul0P3CBX9CBjTbi1l4ZxCgq\nAEEbNwOx48sPewhUbSzIOU3awZ5eED5W3ReBwgp5SdVD2zUsV5lALlluzRLmNKDJ\nT5iB7dqMvBTNHt8IxQ0dm3wAp1yBTnE2rB46+AZbiKq+VZicpR8m3DOII5Kd299H\n2rjd2j8Ra7FuT+iYIt40zxqS/mwJZ0dO23sx2/YJxwvhZI4woncivYX+pCZHKlFi\nf7CPS9FGMPtzF/vIl05YdBFllPUJDBnIOkH6zEnyhPwSSJklWre+8wcAZnvVMxKZ\nsMheIFQgjzgH+l+wwRB+FO+wTOWXhTMZlG6IVFMb6M0CgYEA62kubKcauiv7mkMB\nD3AWSYXJpH1+ilm0Po97BpBRpnENk5bjjOPxHwZ1WSeLzn9nhAqgUJtoEQt4cpjh\nP5ZPD11SSS99SXfjRoiAwewioyaDFTA86NYBWk/6AvQI9tQvP5rBtDnSPXGJNYwM\n/fUnacNSjN+TxpSzsHn81mPAQosCgYEA30KArXy4yzAqJFd0ga4s/UkicwVcZzoE\ntQdCe4qcX+FxZNxsMX8UcxORFBnRNIOnZqFJ7Bap16o83sYZU8/E2hSgu755QOUF\ni/mbczGwOxjrdtKzMpQcwgPba/kBLJrejXS+Vmh7FBiy1XqtkPs7IMws01vlS97N\nRYNdJUHJav8CgYEAllVpLEHas6F635yChNVTpkgl6UGrGbcHgBwouJxZSC1SOjpV\nvpeiV+nL7s9uXMTH2m7eyhs0bg4hMS2oSu82Nd2mus30+IHzRgvODgk6ZW4mr9VK\nUHa6Dm6cfl5Riy8drUSrBukV9d8XfHafpV51ePkfMo9k06AK0FxWtqKlGNkCgYBo\nC4gIUc2U87dQBGnJXbCdwY2KaP8tJD65Vs7G4EwL6vZ7eLX7Qyv2jTHZWkbC4HAN\nRjE7EzzHwxBnCY8YHgWxVFer5xJ/CbxSBVtKjeeBQxXI5Fyav6e/Syjg4sSHUw1Q\ngw2JG1vwe6osDuYAYPSnTj+9qF/twcGMGbI5ALWrZQKBgQCMLqigE/cMstyNmDfN\n3pNcpMgqzVrRY5/zXeI5K5zcc+iIzADt861nQUBFF4yD67uLLowad4VzmtFYIQTS\n7R8Kmu4jOGktNYG8OGuy/RO/Z+MGq43KkkDTHNLO1YzzPrHiSdiS4ba5IpHFV4U4\nRczm1b3kPdW9PAhJSEFBHEBbhA==\n-----END PRIVATE KEY-----\n"
              path: '/secrets/oidc.jwk.RS256.pem'
            certificate_chain:
              path: '/secrets.oidc.jwk.RS256.crt'

        clients:
          - client_id: 'argocd'
            client_name: 'Argo CD'
            client_secret:
              value: '$pbkdf2-sha512$310000$c8p78n7pUMln0jzvd4aK4Q$JNRBzwAo0ek5qKn50cFzzvE9RXV88h1wJn5KGiHrD0YKtZaR/nCb2CJPOsKaPK0hjf.9yHxzQGZziziccp6Yng'
              path: /secret/oidc.client.argocd.value
            public: false
            authorization_policy: 'one_factor'
            redirect_uris:
              - https://argocd.intropin.be/auth/callback
            scopes:
              - openid
              - groups
              - email
              - profile
            userinfo_signed_response_alg: 'none'
