app-template:
  defaultPodOptions:
    securityContext:
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 0
      fsGroupChangePolicy: "Always"
  controllers:
    main:
      containers:
        main:
          image:
            repository: registry.hub.docker.com/linuxserver/qbittorrent
            tag: 20.04.1
  service:
    main:
      annotations:
        tailscale.com/expose: "true"
      controller: main
      ports:
        http:
          port: 80
          targetPort: 8080
        trnt-tcp:
          port: 6881
          targetPort: 6881
          protocol: TCP
        trnt-udp:
          port: 6881
          targetPort: 6881
          protocol: UDP
  persistence:
    config:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 1Gi
      storageClass: local-path-ssd
      globalMounts:
        - path: /config
    qbittorrent-downloads:
      enabled: true
      type: persistentVolumeClaim
      existingClaim: "qbittorrent-downloads"
      globalMounts:
        - path: /downloads
