argo-cd:
  server:
    service:
      annotations:
        tailscale.com/expose: "true"
    replicas: 1
    pdb:
      enabled: true
      minAvailable: 1
    extraArgs: 
      - "--insecure"
  configs:
    params:
      applicationsetcontroller.policy: "create-only"
      server.disable.auth: true
    cm:
      admin.enabled: "false"
      url: http://argocd-argocd-server
      exec.enabled: "true"
      resource.compareoptions: |
        ignoreAggregatedRoles: true
        ignoreResourceStatusField: crd
      server.insecure: true
  controller:
    replicas: 1
    pdb:
      enabled: true
      minAvailable: 1
  repoServer:
    replicas: 1
  applicationSet:
    replicaCount: 1
  dex:
    enabled: true
    pdb:
      enabled: true
      minAvailable: 1
  global:
    priorityClassName: system-cluster-critical
