argo-cd:
  server:
    replicas: 1
    pdb:
      enabled: true
      minAvailable: 1
    ingress:
      enabled: true
      hosts:
        - &host argocd.intropin.be
      annotations:
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        nginx.org/websocket-services: "argocd-server"
        cert-manager.io/cluster-issuer: "issuer"
        nginx.ingress.kubernetes.io/auth-method: GET
        nginx.ingress.kubernetes.io/auth-url: http://authelia.core.svc.cluster.local:9091/api/verify
        nginx.ingress.kubernetes.io/auth-signin: https://auth.intropin.be?rm=$request_method
        nginx.ingress.kubernetes.io/auth-response-headers: Remote-User,Remote-Name,Remote-Groups,Remote-Email
        nginx.ingress.kubernetes.io/auth-snippet: |
          proxy_set_header X-Forwarded-Method $request_method;       
      tls:
        - hosts:
            - *host
          secretName: argocd-letsencrypt-certificate

  configs:
    params:
      applicationsetcontroller.policy: "create-only"
      server.disable.auth: true
    cm:
      admin.enabled: "true"
      url: https://argocd.intropin.be
      exec.enabled: "true"
      resource.compareoptions: |
        ignoreAggregatedRoles: true
        ignoreResourceStatusField: crd

    rbac:
      policy.csv: |
        g, argo-admin, role:admin
        g, admins, role:admin
        g, ArgoCD Admins, role:admin

  controller:
    replicas: 1
    pdb:
      enabled: true
      minAvailable: 1

  repoServer:
    replicas: 1

  applicationSet:
    replicaCount: 1

  dex:
    enabled: true
    pdb:
      enabled: true
      minAvailable: 1

  global:
    priorityClassName: system-cluster-critical
