argo-cd:
  server:
    replicas: 1
    pdb:
      enabled: true
      minAvailable: 1
    ingress:
      enabled: true
      hosts:
        - &host argocd.intropin.be
      annotations:
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        nginx.org/websocket-services: "argocd-server"
        cert-manager.io/cluster-issuer: "issuer"
      tls:
        - hosts:
            - *host
          secretName: argocd-letsencrypt-certificate

  configs:
    params:
      applicationsetcontroller.policy: "create-only"
    cm:
      admin.enabled: "true"
      url: https://argocd.intropin.be
      exec.enabled: "true"
      resource.compareoptions: |
        ignoreAggregatedRoles: true
        ignoreResourceStatusField: crd
      oidc.config: |
        name: Authelia
        issuer: https://auth.intropin.be
        clientID: $argocd-secret:clientID
        clientSecret: $argocd-secret:clientSecret
        requestedScopes:
          - openid
          - profile
          - email
          - groups
        oidc.tls.insecure.skip.verify: true
    secret:
      extra:
        clientID: "argocd"  
        clientSecret: "g3B8QGa.4~c9scA2GdWoz.BXgo4cMOW5YgoEX46XqrTBbAhqN~K6-YoZ.YjsBqfLtX1a3Jnw"

    rbac:
      policy.csv: |
        g, argo-admin, role:admin
        g, admins, role:admin

  rbac:
    policy.csv: |
      g, argo-admin, role:admin
      g, admins, role:admin

  controller:
    replicas: 1
    pdb:
      enabled: true
      minAvailable: 1

  repoServer:
    replicas: 1

  applicationSet:
    replicaCount: 1

  dex:
    enabled: true
    pdb:
      enabled: true
      minAvailable: 1

  global:
    priorityClassName: system-cluster-critical
