app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: ghcr.io/onedr0p/sonarr
            tag: 4.0.5.1710
  service:
    main:
      controller: main
      ports:
        http:
          port: &port 8989
  ingress:
    main:
      enabled: true
      annotations:
        nginx.org/websocket-services: "sonarr"
        nginx.ingress.kubernetes.io/auth-method: GET
        nginx.ingress.kubernetes.io/auth-url: http://authelia.core.svc.cluster.local:80/api/verify
        nginx.ingress.kubernetes.io/auth-signin: https://auth.intropin.be?rm=$request_method
        nginx.ingress.kubernetes.io/auth-response-headers: Remote-User,Remote-Name,Remote-Groups,Remote-Email
        nginx.ingress.kubernetes.io/auth-snippet: "proxy_set_header X-Forwarded-Method $request_method;       \n"
        cert-manager.io/cluster-issuer: "issuer"
      hosts:
        - host: &host sonarr.intropin.be
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: main
                port: *port
      tls:
        - secretName: sonarr-letsencrypt-certificate
          hosts: [*host]
  podSecurityContext:
    runAsUser: 568
    runAsGroup: 568
    fsGroup: 568
    fsGroupChangePolicy: "Always"
  persistence:
    config:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 1Gi
      storageClass: local-path-ssd
      globalMounts:
        - path: /config
    downloads:
      enabled: true
      type: persistentVolumeClaim
      existingClaim: "sab-downloads"
      globalMounts:
        - path: /downloads
    media:
      enabled: true
      type: persistentVolumeClaim
      existingClaim: "media"
      globalMounts:
        - path: /media
