authentik:

  env:
    AUTHENTIK_COOKIE_DOMAIN: intropin.be

  authentik:
    postgresql:
      host: authentik-database-rw
      password: "inscure_password"
    redis:
      host: authentik-redis-master
    secret_key: "PleaseGenerateA50CharKey"
  ingress:
    enabled: true
    annotations:
      external-dns.home.arpa/enabled: "true"
    hosts:
      - host: authentik.intropin.be
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: authentik-letsencrypt-certificate
        hosts:
          - authentik.intropin.be

  postgresql:
    enabled: true
    password: "inscure_password"

  redis:
    enabled: true

  priorityClassName: system-cluster-critical


  resources:
    server:
      requests:
        cpu: 5m

    worker:
      requests:
        cpu: 5m
