---
clusterName: echel
talosVersion: 1.4.0
kubernetesVersion: v1.27.1
endpoint: https://192.168.0.31:6443
domain: cluster.local
cniConfig:
  name: flannel
nodes:
  - hostname: master-01
    ipAddress: 192.168.0.31
    installDisk: /dev/sda
    controlPlane: true
    nameservers:
      - 1.1.1.1
      - 8.8.8.8
    networkInterfaces:
      - interface: eth0
        addresses:
          - 192.168.0.31/24
        mtu: 1500
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.0.1
    patches:
      - |-
        - op: add
          path: /machine/disks
          value:
            - device: /dev/sdb
              partitions:
                - mountpoint: /var/mnt/ssd
            - device: /dev/sdc
              partitions:
                - mountpoint: /var/mnt/hdd
controlPlane:
  patches:
    - |-
      - op: add
        path: /cluster/allowSchedulingOnMasters
        value: true
