app-template:
  defaultPodOptions:
    enableServiceLinks: false

  controllers:
    main:
      containers:
        main:
          image:
            repository: ghcr.io/swatfish/skybrief-backend
            tag: latest
          env:
            ALLOWED_ORIGINS: "https://vcom.dev"
  service:
    main:
      controller: main
      ports:
        http:
          port: 3000
          targetPort: 3000

  persistence:
    # SQLite database and app data
    data:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 5Gi
      storageClass: local-path-ssd
      globalMounts:
        - path: /app/data

  route:
    main:
      enabled: true
      kind: HTTPRoute
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      hostnames:
        - skybrief-backend.intropin.be
      parentRefs:
        - name: envoy-gateway
          namespace: default
          sectionName: https
