app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: ghcr.io/lloesche/valheim-server
            tag: latest
          env:
            SERVER_NAME: bambi 
            WORLD_NAME: bambi
            SERVER_PASS: ABSOunited
            VALHEIM_PLUS: false
  service:
    main:
      controller: main
      ports:
        http:
          port: 9001
          targetPort: 9001
        game1:
          port: 2456
          targetPort: 2456
          protocol: UDP
        game2:
          port: 2457
          targetPort: 2457
          protocol: UDP
        game3:
          port: 2458
          targetPort: 2458
          protocol: UDP
      type: LoadBalancer
      loadBalancerIP: 192.168.0.70
  persistence:
    config:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 1Gi
      storageClass: local-path-ssd
      globalMounts:
        - path: /config
    data:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 1Gi
      storageClass: local-path-ssd
      globalMounts:
        - path: /opt/valheim
