argo-workflows:
  server:
    ingress:
      enabled: true
      hostname: workflows.intropin.be
      tls: true
      annotations:
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        cert-manager.io/cluster-issuer: "issuer"
      hosts:
        - host: 
          - &host workflows.intropin.be
      paths:
        - /
      tls:
        - secretName: workflows-letsencrypt-certificate
          hosts: [*host]
