firefly-iii-stack:
  firefly-iii:
    config:
      env:
        DB_HOST: firefly-db
        DEFAULT_LANGUAGE: en_US
        DEFAULT_LOCALE: equal
        TRUSTED_PROXIES: "**"
        TZ: Europe/Brussels
        APP_KEY: 9xmisGDZACsd5kDc9RS9fLPSt5WZGjea
        DB_HOST: "firefly-iii-firefly-db"
      envValueFrom: {}
      existingSecret: ''
  importer:
    config:
      env:
        FIREFLY_III_URL: "https://firefly.intropin.be"
