---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helm-apps-extra-manifests
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/Yan-Solo/homelab-ng.git
        revision: HEAD
        directories:
          - path: "kubernetes/helm/*/*/manifests"
  syncPolicy:
    preserveResourcesOnDeletion: true
  template:
    metadata:
      name: "{{path[3]}}-manifests"
    spec:
      project: default
      source:
        repoURL: https://github.com/Yan-Solo/homelab-ng.git
        targetRevision: HEAD
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{path[2]}}"

      syncPolicy:
        syncOptions:
          - RespectIgnoreDifferences=true
          - CreateNamespace=true
          - ServerSideApply=true
        automated:
          prune: true
          selfHeal: true
