---
app-template:
  image:
    repository: registry.hub.docker.com/bellamy/wallos
    tag: latest
  service:
    main:
      ports:
        http:
          port: 80

  ingress:
    main:
      enabled: true
      annotations:
        nginx.org/websocket-services: "wallos"
        cert-manager.io/cluster-issuer: "issuer"
      hosts:
        - host: &host wallos.intropin.be
          paths:
            - path: /
              pathType: Prefix
              service:
                port: 80
      tls:
        - secretName: wallos-letsencrypt-certificate
          hosts: 
            - *host
  persistence:
    db:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 1Gi
      mountpath: /var/www/html/db
      storageClass: local-path-ssd
    logos:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 1Gi
      mountpath: /var/www/html/images/uploads/logos
      storageClass: local-path-ssd
