apiVersion: v2
name: sparkyfitness
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
- name: sparkyfitness
  version: 0.3.0
  repository: https://ghcr.io/codewithcj/charts/sparkyfitness
