sparkyfitness:
  frontend:
    port: 8080
  httpRoute:
    enabled: true
    hostname: sparkyfitness.sunnyvale.be
    parentRef:
      name: envoy-gateway
      namespace: default
      sectionName: https
