app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: ghcr.io/koenkk/zigbee2mqtt
            tag: 1.35.1
  service:
    main:
      ports:
        http:
          port: 8080
  ingress:
    main:
      enabled: true
      annotations:
        nginx.org/websocket-services: "zigbee2mqtt"
        cert-manager.io/cluster-issuer: "issuer"
      hosts:
        - host: &host zigbee2mqtt.intropin.be
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: 8080
      tls:
        - secretName: zigbee2mqtt-letsencrypt-certificate
          hosts:
            - *host
  persistence:
    config:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 1Gi
      storageClass: local-path-ssd
      globalMounts:
        - path: /config
