app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: ghcr.io/koenkk/zigbee2mqtt
            tag: 1.35.1
  service:
    main:
      ports:
        http:
          port: 8080
  ingress:
    main:
      enabled: true
      annotations:
        nginx.org/websocket-services: "zigbee2mqtt"
        cert-manager.io/cluster-issuer: "issuer"
      hosts:
        - host: &host zigbee2mqtt.intropin.be
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: 8080
      tls:
        - secretName: zigbee2mqtt-letsencrypt-certificate
          hosts:
            - *host
  podSecurityContext:
    runAsUser: 568
    runAsGroup: 568
    fsGroup: 568
    fsGroupChangePolicy: "Always"
  persistence:
    config:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 1Gi
      storageClass: local-path-ssd
      globalMounts:
        - path: /config
    usb:
      enabled: true
      type: hostPath
      hostPath: /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20230829184048-if00
      mountPath: /dev/ttyACM0
      globalMounts:
        - path: /dev/ttyACM0
