app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: ghcr.io/home-assistant/home-assistant
            tag: 2024.1.5
  service:
    main:
      ports:
        http:
          port: 8123
  ingress:
    main:
      enabled: true
      annotations:
        nginx.org/websocket-services: "home-assistant"
        cert-manager.io/cluster-issuer: "issuer"
      hosts:
        - host: &host home-assistant.intropin.be
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: 8123
      tls:
        - secretName: home-assistant-letsencrypt-certificate
          hosts:
            - *host
  persistence:
    config:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 1Gi
      storageClass: local-path-ssd
      globalMounts:
        - path: /config
    configuration:
      enabled: true
      type: configMap
      name: configuration
      advancedMounts:
        main:
          main:
            - path: /config/configuration.yaml
              readOnly: true
              subPath: configuration.yaml
    usb:
      enabled: true
      type: hostPath
      hostPath: /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20230829184048-if00
      mountPath: /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20230829184048-if00
      globalMounts:
        - path: /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20230829184048-if00
  defaultPodOptions:
    hostNetwork: true
