---
app-template:
  image:
    repository: ghcr.io/home-assistant/home-assistant
    tag: 2023.1.7
  service:
    main:
      ports:
        http:
          port: 8123

  ingress:
    main:
      enabled: true
      annotations:
        nginx.org/websocket-services: "home-assistant"
        nginx.ingress.kubernetes.io/auth-method: GET
        nginx.ingress.kubernetes.io/auth-url: http://authelia.core.svc.cluster.local/api/verify
        nginx.ingress.kubernetes.io/auth-signin: https://auth.intropin.be?rm=$request_method
        nginx.ingress.kubernetes.io/auth-response-headers: Remote-User,Remote-Name,Remote-Groups,Remote-Email
        nginx.ingress.kubernetes.io/auth-snippet: |
          proxy_set_header X-Forwarded-Method $request_method;       
        cert-manager.io/cluster-issuer: "issuer"
      hosts:
        - host: &host home-assistant.intropin.be
          paths:
            - path: /
              pathType: Prefix
              service:
                port: 8123
      tls:
        - secretName: home-assistant-letsencrypt-certificate
          hosts: [*host]
  persistence:
    config:
      enabled: true
      type: custom
      volumeSpec:
        configMap:
          name: configuration
      subPath:
        - path: configuration.yaml
          mountPath: /config/configuration.yaml
