app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: ghcr.io/home-assistant/home-assistant
            tag: 2023.12.0
  service:
    main:
      ports:
        http:
          port: 8123
  ingress:
    main:
      enabled: true
      annotations:
        nginx.org/websocket-services: "home-assistant"
        cert-manager.io/cluster-issuer: "issuer"
      hosts:
        - host: &host home-assistant.intropin.be
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: 8123
      tls:
        - secretName: home-assistant-letsencrypt-certificate
          hosts:
            - *host
  persistence:
    config:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 1Gi
      mountpath: /config
      storageClass: local-path-ssd
    configuration:
      enabled: true
      type: configMap
      name: configuration
      mountPath: /config/configuration.yaml
  hostNetwork: true
