immich:
  image:
    tag: v1.82.0
  immich:
    persistence:
      library:
        existingClaim: immich-library
  postgresql:
    enabled: true
  redis:
    enabled: true
  proxy:
    ingress:
      main:
        enabled: true
        annotations:
          nginx.org/websocket-services: "immich"
          cert-manager.io/cluster-issuer: "issuer"
        hosts:
          - host: &host photos.intropin.be
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: 8080
        tls:
          - secretName: photos-letsencrypt-certificate
            hosts:
              - *host
