---
immich:
  immich:
    persistence:
      library:
        existingClaim: immich-library
  postgresql:
    enabled: true
  redis:
    enabled: true
  proxy:
    ingress:
      main:
        enabled: true
        annotations:
          nginx.org/websocket-services: "immich"
          cert-manager.io/cluster-issuer: "issuer"
        hosts:
          - host: &host immich.intropin.be
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: 8123
        tls:
          - secretName: immich-letsencrypt-certificate
            hosts: 
              - *host
