app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: lscr.io/linuxserver/plex
            tag: 1.41.6
          env:
            PLEX_CLAIM: "claim-T9y4LNfsdsvhJ95FrH2W"
  service:
    main:
      annotations:
        tailscale.com/expose: "true"
      controller: main
      ports:
        http:
          port: 80
          targetPort: 32400
      type: LoadBalancer
      loadBalancerIP: 192.168.0.63
  persistence:
    config:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 1Gi
      storageClass: local-path-ssd
      globalMounts:
        - path: /config
    media:
      enabled: true
      type: persistentVolumeClaim
      existingClaim: "media"
      globalMounts:
        - path: /data
