apiVersion: v1
kind: Secret
metadata:
  name: n8n-secret
type: Opaque
stringData:
  secret.json: |
    {
      DB_POSTGRESDB_USER: n8n,
      DB_POSTGRESDB_PASSWORD: 1KZOjlRTiqgSeVuA4lzf0sIeKt9no7C2DXbW3r4zdbagcL0zE6LWEVvzaRMCoshn,
      N8N_ENCRYPTION_KEY: "c29tZS1yYW5kb20tc3RyaW5nCg==",
    }
