---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: &name n8n-database
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised
  bootstrap:
#    recovery:
#      database: n8n
#      owner: n8n
#      source: *name
#     Create a new DB, hopefully never needed!
     initdb:
       database: n8n
       owner: n8n
  storage:
    storageClass: local-path-ssd
    size: 5Gi

  monitoring:
    enablePodMonitor: true

  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
    podAntiAffinityType: preferred
