app-template:
  defaultPodOptions:
    securityContext:
      runAsUser: 568 
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "Always"
  controllers:
    main:
      containers:
        main:
          image:
            repository: lscr.io/linuxserver/lazylibrarian
            tag: version-57e05989
  service:
    main:
      controller: main
      annotations:
        tailscale.com/expose: "true"
        tailscale.com/hostname: "lazylibrarian"
      ports:
        http:
          port: 80
          targetPort: &port 5299
  persistence:
    config:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 1Gi
      storageClass: local-path-ssd
      globalMounts:
        - path: /config
      forceRename: lazylibrarian-config
    books:
      enabled: true
      type: persistentVolumeClaim
      existingClaim: "media"
      globalMounts:
        - path: /books
    downlods:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 1Gi
      globalMounts:
        - path: /downloads
      forceRename: lazylibrarian-books
