app-template:
  defaultPodOptions:
    securityContext:
      runAsUser: 911
      runAsGroup: 1001
      fsGroup: 1001
      fsGroupChangePolicy: "Always"
  controllers:
    main:
      containers:
        main:
          image:
            repository: lscr.io/linuxserver/lazylibrarian
            tag: e65abd21-ls144
          env:
            PUID: 911
            PGID: 1001
  service:
    main:
      controller: main
      annotations:
        tailscale.com/expose: "true"
      ports:
        http:
          port: 80
          targetPort: 5299
  podSecurityContext:
    runAsUser: 911
    runAsGroup: 1001
    fsGroup: 1001
    fsGroupChangePolicy: "Always"
  persistence:
    config:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 1Gi
      storageClass: local-path-ssd
      globalMounts:
        - path: /config
    qbittorrent-downloads:
      enabled: true
      type: persistentVolumeClaim
      existingClaim: "qbittorrent-downloads"
      globalMounts:
        - path: /downloads
    media:
      enabled: true
      type: persistentVolumeClaim
      existingClaim: "media"
      globalMounts:
        - path: /books
