app-template:
  defaultPodOptions:
    securityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "Always"
  controllers:
    main:
      containers:
        main:
          image:
            repository: lscr.io/linuxserver/lazylibrarian
            tag: e65abd21-ls144
  service:
    main:
      controller: main
      annotations:
        tailscale.com/expose: "true"
      ports:
        http:
          port: 80
          targetPort: &port 8787
  podSecurityContext:
    runAsUser: 568
    runAsGroup: 568
    fsGroup: 568
    fsGroupChangePolicy: "Always"
  persistence:
    config:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 1Gi
      storageClass: local-path-ssd
      globalMounts:
        - path: /config
    qbittorrent-downloads:
      enabled: true
      type: persistentVolumeClaim
      existingClaim: "qbittorrent-downloads"
      globalMounts:
        - path: /qbittorrent-downloads
    media:
      enabled: true
      type: persistentVolumeClaim
      existingClaim: "media"
      globalMounts:
        - path: /books
