app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: registry.gitlab.com/smoores/storyteller
            tag: latest
  service:
    main:
      annotations:
        tailscale.com/expose: "true"
      controller: main
      ports:
        http:
          port: 80
          targetPort: &port 8001
  persistence:
    config:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 1Gi
      storageClass: local-path-ssd
      globalMounts:
        - path: /config
    media:
      enabled: true
      type: persistentVolumeClaim
      existingClaim: "media"
      globalMounts:
        - path: /data
