---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: skybrief-backend-tls
  namespace: default
spec:
  secretName: skybrief-backend-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
  - skybrief-backend.intropin.be
