app-template:
  defaultPodOptions:
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
  controllers:
    main:
      containers:
        main:
          image:
            repository: registry.hub.docker.com/homeassistant/home-assistant
            tag: 2026.4
          securityContext:
            capabilities:
              add:
                - NET_RAW
                - CAP_SYS_ADMIN
  service:
    main:
      controller: main
      ports:
        http:
          port: 80
          targetPort: 8123
      type: LoadBalancer
      loadBalancerIP: 192.168.0.63
  route:
    main:
      enabled: true
      kind: HTTPRoute
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      hostnames:
        - home-assistant.sunnyvale.be
      parentRefs:
        - name: envoy-gateway
          namespace: default
          sectionName: https
  persistence:
    config:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 1Gi
      storageClass: local-path-ssd
      globalMounts:
        - path: /config
      forceRename: home-assistant-config
    media-dummy:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 1Gi
      storageClass: local-path-hdd
      globalMounts:
        - path: /media-dummy
