kube-prometheus-stack:
  nameOverride: "prometheus"
  fullNameOverride: "prometheus"
  alertmanager:
    enabled: false
  grafana:
    fullNameOverride: grafana
    defaultDashboardsTimezone: Europe/Brussels
    grafana.ini: 
      auth:
        disable_login_form: true
      auth.anonymous:
        enabled: true
        org_name: Intropin
        org_role: Admin
      auth.basic:
        enabled: false
      server:
        domain: "grafana.intropin.be"
        root_url: "https://grafana.intropin.be/"
    ingress:
      enabled: true
      annotations:
        nginx.org/websocket-services: "prometheus-grafana"
        cert-manager.io/cluster-issuer: "issuer"
      hosts:
        - prometheus-grafana.intropin.be
      tls:
        - secretName: prometheus-grafana-letsencrypt-certificate
          hosts:
            - prometheus-grafana.intropin.be
  prometheus:
    fullNameOverride: prometheus
    prometheusSpec:
      retention: 60d
      retentionSize: "180GB"
      walCompression: true
      replicas: 1
      podMonitorSelectorNilUsesHelmValues: false
      serviceMonitorSelectorNilUsesHelmValues: false
      ruleSelectorNilUsesHelmValues: false
      resources:
        limits:
          memory: 5Gi
        requests:
          cpu: 1500m
          memory: 3.5Gi
      storageSpec:
        emptyDir:
          medium: Memory

    ingress:
      enabled: true
      annotations:
        hajimari.io/group: "Monitoring"
        kubernetes.io/ingress-allow-http: "false"
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8"
      hosts:
        - prometheus.intropin.be
      tls:
        - secretName: prometheus-letsencrypt-certificate
          hosts:
            - prometheus.intropin.be
  prometheusOperator:
    admissionWebhooks:
      certManager:
        enabled: true
    resources:
      limits:
        cpu: 100m
        memory: 200Mi
      requests:
        cpu: 100m
        memory: 100Mi
  kubeEtcd:
    enabled: true
    endpoints:
    - 192.168.0.31
    service:
      enabled: true
      port: 2381
      targetPort: 2381

kubeScheduler:
  enabled: true
  endpoints:
  - 192.168.0.31
  service:
    enabled: true
  serviceMonitor:
    enabled: true
    scheme: https
    insecureSkipVerify: true

kubeProxy:
  enabled: true
  endpoints:
  - 192.168.0.31

kubeStateMetrics:
  enabled: true
