---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: core
spec:
  interval: 60m
  chart:
    spec:
      chart: cert-manager
      version: '1.11.1'
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: flux-system
      interval: 60m
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  valuesFrom:
    - kind: ConfigMap
      name: cert-manager-helm-values
