app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: registry.hub.docker.com/fallenbagel/jellyseerr
            tag: 2.7.3
  service:
    main:
      annotations:
        tailscale.com/expose: "true"
        tailscale.com/hostname: "jellyseerr"
      controller: main
      ports:
        http:
          port: 80
          targetPort: 5055
  persistence:
    config:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 1Gi
      storageClass: local-path-ssd
      globalMounts:
        - path: /app/config
      forceRename: jellyseerr-config
