app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: registry.hub.docker.com/fallenbagel/jellyseerr
            tag: 2.7.3
  service:
    main:
      controller: main
      ports:
        http:
          port: 80
          targetPort: 5055
  route:
    main:
      enabled: true
      kind: HTTPRoute
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      hostnames:
        - jellyseerr.intropin.be
      parentRefs:
        - name: envoy-gateway
          namespace: default
          sectionName: https
  persistence:
    config:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 1Gi
      storageClass: local-path-ssd
      globalMounts:
        - path: /app/config
      forceRename: jellyseerr-config
