---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-downloads
spec:
  storageClassName: local-path-ssd
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500G
