app-template:
  defaultPodOptions:
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
  controllers:
    main:
      containers:
        main:
          image:
            repository: ghcr.io/koenkk/zigbee2mqtt
            tag: 2.2.1
          securityContext:
            capabilities:
              add:
                - CAP_SYS_ADMIN
                - SYS_RAWIO
            privileged: true
            runAsUser: true
  service:
    main:
      controller: main
      annotations:
        tailscale.com/expose: "true"
      ports:
        http:
          port: 80
          targetPort: 8080
  persistence:
    data:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 1Gi
      storageClass: local-path-ssd
      globalMounts:
        - path: /app/data
    zigbee-dongle:
      enabled: true
      type: hostPath
      hostPath: /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20230829184048-if00
      mountPath: /dev/ttyACM0
      readOnly: false
