app-template:
  defaultPodOptions:
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
  controllers:
    main:
      containers:
        main:
          image:
            repository: ghcr.io/koenkk/zigbee2mqtt
            tag: 2.2.1
          securityContext:
            capabilities:
              add:
                - CAP_SYS_ADMIN
                - SYS_RAWIO
            privileged: true
            runAsUser: 0
          # env:
          #   ZIGBEE2MQTT_DATA: /app
          #   ZIGBEE2MQTT_CONFIG_MQTT_SERVER: mqtt://mosquitto
          #   ZIGBEE2MQTT_CONFIG_MQTT_BASE_TOPIC: zigbee2mqtt
          #   ZIGBEE2MQTT_CONFIG_PERMIT_JOIN: false
          #   ZIGBEE2MQTT_CONFIG_ADVANCED_CHANNEL: 15
          #   ZIGBEE2MQTT_CONFIG_AVAILABILITY_ACTIVE_TIMEOUT: 60
          #   ZIGBEE2MQTT_CONFIG_AVAILABILITY_PASSIVE_TIMEOUT: 2000
          #   ZIGBEE2MQTT_CONFIG_DEVICE_OPTIONS_RETAIN: true
          #   ZIGBEE2MQTT_CONFIG_FRONTEND_ENABLED: true
          #   ZIGBEE2MQTT_CONFIG_FRONTEND_PORT: 8080
          #   ZIGBEE2MQTT_CONFIG_HOMEASSISTANT_ENABLED: true
          #   ZIGBEE2MQTT_CONFIG_HOMEASSISTANT_DISCOVERY_TOPIC: homeassistant
          #   ZIGBEE2MQTT_CONFIG_HOMEASSISTANT_STATUS_TOPIC: homeassistant/status
          #   ZIGBEE2MQTT_CONFIG_MQTT_INCLUDE_DEVICE_INFORMATION: true
          #   ZIGBEE2MQTT_CONFIG_MQTT_KEEPALIVE: 60
          #   ZIGBEE2MQTT_CONFIG_MQTT_SERVER: mqtt://mosquitto
          #   ZIGBEE2MQTT_CONFIG_MQTT_VERSION: 5
          #   ZIGBEE2MQTT_CONFIG_PERMIT_JOIN: true
          #   ZIGBEE2MQTT_CONFIG_SERIAL_BAUDRATE: 115200
          #   ZIGBEE2MQTT_CONFIG_SERIAL_ADAPTER: ember
  service:
    main:
      controller: main
      annotations:
        tailscale.com/expose: "true"
        tailscale.com/hostname: "home-assistant-zigbee2mqtt"
      ports:
        http:
          port: 80
          targetPort: 8080
  persistence:
    data:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 1Gi
      storageClass: local-path-ssd
      globalMounts:
        - path: /app/data
    zigbee-dongle:
      enabled: true
      type: hostPath
      hostPath: /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20230829184048-if00
      globalMounts:
        - path: /dev/ttyACM0
