app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: adguard/adguardhome
            tag: latest
  service:
    main:
      controller: main
      annotations:
        tailscale.com/expose: "true"
      ports:
        http:
          port: 80
          targetPort: 80
        dns:
          port: 53
          targetPort: 53
      type: LoadBalancer
      loadBalancerIP: 192.168.0.62
  persistence:
    config:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 1Gi
      storageClass: local-path-ssd
      globalMounts:
        - path: /opt/adguardhome/conf
    work:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 1Gi
      storageClass: local-path-ssd
      globalMounts:
        - path: /opt/adguardhome/work
