app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: ghcr.io/onedr0p/sabnzbd
            tag: 4.2.3
  service:
    main:
      controller: main
      ports:
        http:
          port: &port 8080
  ingress:
    main:
      enabled: true
      annotations:
        nginx.org/websocket-services: "sabnzbd"
        cert-manager.io/cluster-issuer: "issuer"
        nginx.ingress.kubernetes.io/auth-method: GET
        nginx.ingress.kubernetes.io/auth-url: http://authelia.core.svc.cluster.local:80/api/verify
        nginx.ingress.kubernetes.io/auth-signin: https://auth.intropin.be?rm=$request_method
        nginx.ingress.kubernetes.io/auth-response-headers: Remote-User,Remote-Name,Remote-Groups,Remote-Email
        nginx.ingress.kubernetes.io/auth-snippet: "proxy_set_header X-Forwarded-Method $request_method;       \n"
      hosts:
        - host: &host sabnzbd.intropin.be
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: 8080
      tls:
        - secretName: sabnzbd-letsencrypt-certificate
          hosts: [*host]
  podSecurityContext:
    runAsUser: 568
    runAsGroup: 568
    fsGroup: 568
    fsGroupChangePolicy: "Always"
  persistence:
    config:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 1Gi
      globalMounts:
        - path: /config
      storageClass: local-path-ssd
    downloads:
      enabled: true
      type: persistentVolumeClaim
      existingClaim: "sab-downloads"
      globalMounts:
        - path: /downloads
    media:
      enabled: true
      type: persistentVolumeClaim
      existingClaim: "media"
      globalMounts:
        - path: /media
