app-template:
  image:
    repository: ghcr.io/onedr0p/sabnzbd
    tag: 3.7.1
  podSecurityContext:
    runAsUser: 568
    runAsGroup: 568
    fsGroup: 568

  service:
    main:
      ports:
        http:
          port: &port 8080

  ingress:
    main:
      enabled: true
      annotations:
        nginx.org/websocket-services: "sabnzbd"
        cert-manager.io/cluster-issuer: "issuer"
      hosts:
        - host: &host sabnzbd.intropin.be
          paths:
            - path: /
              pathType: Prefix
              service:
                port: 8080
      tls:
        - secretName: sabnzbd-letsencrypt-certificate
          hosts: [*host]

  podSecurityContext:
    runAsUser: 568
    runAsGroup: 568
    fsGroup: 568
    fsGroupChangePolicy: "Always"

  persistence:
    config:
      enabled: true
      type: pvc
      accessMode: ReadWriteOnce
      size: 1Gi
      mountpath: /config
      storageClass: ssd-local-path

    media:
      enabled: true
      type: pvc
      existingClaim: "media"
      mountpath: /media
