app-template:
  image:
    repository: ghcr.io/onedr0p/sabnzbd
    tag: 3.7.1
  podSecurityContext:
    runAsUser: 568
    runAsGroup: 568
    fsGroup: 568

  service:
    main:
      ports:
        http:
          port: &port 8080

  ingress:
    main:
      enabled: true
      annotations:
        nginx.org/websocket-services: "sabnzbd"
        cert-manager.io/cluster-issuer: "issuer"
        nginx.ingress.kubernetes.io/auth-method: GET
        nginx.ingress.kubernetes.io/auth-url: http://authelia.core.svc.cluster.local:9091/api/verify
        nginx.ingress.kubernetes.io/auth-signin: https://auth.intropin.be?rm=$request_method
        nginx.ingress.kubernetes.io/auth-response-headers: Remote-User,Remote-Name,Remote-Groups,Remote-Email
        nginx.ingress.kubernetes.io/auth-snippet: |
          proxy_set_header X-Forwarded-Method $request_method;       
      hosts:
        - host: &host sabnzbd.intropin.be
          paths:
            - path: /
              pathType: Prefix
              service:
                port: 8080
      tls:
        - secretName: sabnzbd-letsencrypt-certificate
          hosts: [*host]

  podSecurityContext:
    runAsUser: 568
    runAsGroup: 568
    fsGroup: 568
    fsGroupChangePolicy: "Always"
  resources:
    limits:
      cpu: 3333Mi
      memory: 5120M
  persistence:
    config:
      enabled: true
      type: pvc
      accessMode: ReadWriteOnce
      size: 1Gi
      mountpath: /config
      storageClass: local-path-ssd

    media:
      enabled: true
      type: pvc
      existingClaim: "media"
      mountpath: /media
