app-template:
  defaultPodOptions:
    securityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "Always"
  controllers:
    main:
      containers:
        main:
          image:
            repository: ghcr.io/onedr0p/radarr
            tag: 5.20.1.9773
  service:
    main:
      annotations:
        tailscale.com/expose: "true"
      controller: main
      ports:
        http:
          port: 80
          targetPort: &port 7878
  persistence:
    config:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 1Gi
      storageClass: local-path-ssd
      globalMounts:
        - path: /config
    downloads:
      enabled: true
      type: persistentVolumeClaim
      existingClaim: "sab-downloads"
      globalMounts:
        - path: /downloads
    media:
      enabled: true
      type: persistentVolumeClaim
      existingClaim: "media"
      globalMounts:
        - path: /media
