app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: registry.hub.docker.com/docmost/docmost
            tag: 0.3.1
  service:
    main:
      controller: main
      ports:
        http:
          port: &port 3000
  ingress:
    main:
      enabled: true
      annotations:
        nginx.org/websocket-services: "docmost"
        # nginx.ingress.kubernetes.io/auth-method: GET
        # nginx.ingress.kubernetes.io/auth-url: http://authelia.core.svc.cluster.local/api/authz/auth-request
        # nginx.ingress.kubernetes.io/auth-signin: https://auth.intropin.be?rm=$request_method
        # nginx.ingress.kubernetes.io/auth-response-headers: Remote-User,Remote-Name,Remote-Groups,Remote-Email
        # nginx.ingress.kubernetes.io/auth-snippet: "proxy_set_header X-Forwarded-Method $request_method;       \n"
        cert-manager.io/cluster-issuer: "issuer"
      hosts:
        - host: &host docmost.intropin.be
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: main
                port: *port
      tls:
        - secretName: docmost-letsencrypt-certificate
          hosts: [*host]
  persistence:
    data:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 1Gi
      storageClass: local-path-ssd
      globalMounts:
        - path: /app/data/storage
