---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: core
spec:
  interval: 60m
  chart:
    spec:
      chart: metallb
      version: '0.13.9'
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
      interval: 15m
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  valuesFrom:
    - kind: ConfigMap
      name: metallb-helm-values
