---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-pool
spec:
  addresses:
  - 192.168.0.60-192.168.0.70

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default
