influxdb:
  image:
    repository: "influxdb"
    tag: "2.7.6-alpine"
  setDefaultUser:
    enabled: true
  ingress:
    enabled: true
    annotations:
      nginx.org/websocket-services: "influxdb"
      cert-manager.io/cluster-issuer: "issuer"
    hostname: influxdb.intropin.be
    tls: true
    secretName: influxdb-letsencrypt-certificate
  persistence:
    enabled: true
    size: 8Gi
  env:
    - name: TZ
      value: Europe/Brussels
