influxdb:
  ingress:
    enabled: true
    annotations:
      nginx.org/websocket-services: "home-assistant"
      cert-manager.io/cluster-issuer: "issuer"
    hosts:
      - host: &host home-assistant.intropin.be
        paths:
          - path: /
            pathType: Prefix
            service:
              port: 8123
    tls:
      - secretName: home-assistant-letsencrypt-certificate
        hosts: 
          - *host
  persistence:
    enabled: true
    size: 8Gi
