influxdb:
  ingress:
    enabled: true
    annotations:
      nginx.org/websocket-services: "influxdb"
      cert-manager.io/cluster-issuer: "issuer"
    hosts:
      - host: &host influxdb.intropin.be
        paths:
          - path: /
            pathType: Prefix
            service:
              port: 8086
    tls:
      - secretName: influxdb-letsencrypt-certificate
        hosts: 
          - *host
  persistence:
    enabled: true
    size: 8Gi
