influxdb:
  image:
    tag: "2.4.7-alpine"
  setDefaultUser:
    enabled: true
  ingress:
    enabled: true
    annotations:
      nginx.org/websocket-services: "influxdb"
      cert-manager.io/cluster-issuer: "issuer"
    hostname: influxdb.intropin.be
    tls: true
    secretName: influxdb-letsencrypt-certificate
  persistence:
    enabled: true
    size: 8Gi
