apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia-cm
data:
  configuration.yaml: |
    ---
    theme: light
    jwt_secret: 'secret'
    server: 
      host: 0.0.0.0
      port: 9091
    log:
      level: debug
    default_redirection_url: https://auth.intropin.be
    totp:
      issuer: authelia.com
    authentication_backend:
      file:
        path: /config/users_database.yaml
        password:
          algorithm: argon2id
          iterations: 1
          salt_length: 16
          parallelism: 8
          memory: 64
    access_control:
      default_policy: one_factor
      rules:
        - domain: home-assistant.intropin.be
          policy: one_factor
    identity_providers:
      oidc:
        hmac_secret: QWaxjWwi0TtpHdsssMbYsofllhNFEYOMptH4qMT1dhhpAVhTdUsoGVBnNvsKOiCP
        issuer_private_key: | 
          -----BEGIN RSA PRIVATE KEY-----
          MIIEowIBAAKCAQEAv79FrgNT0sZx278905C44IgDkVjGOntDYpOkXo4wwwVaeyho
          MPleymxMCoTt1e2QREE82KlfjIUpupp4InVS25fUEJUYxQ4lqKx48ApdwQkUE8CG
          RTwThmmx+H+b5mcB9o55L6GbWtdBJLbavIJqFa58O2rB7Tkw9QNcMa8f4ZO/sMz+
          mDLwq4Fs9o4YGxpMnnc/rrxAbSK4emZY/hCg4JrAPbb4TD5aGQN17LSkjb6P/+jp
          KF/5K1NRFytsHLtTRo2mX34hMjVY3BBYdJDkTQ92Oge/4nOXlIDucoQEiqaTOMQH
          7xX4/G8FzHtsHOPcJkxBq9TgxKpC1noko1z0RwIDAQABAoIBACurlmURYO/qPlg7
          8ArVNSX+FEHwJAWBuVEkKxVV8QkZmQffpgsxYENd8tuadsh4OJky+nal7JsGYQCc
          2auPaPWWWLgGHQQUOsN1tH2G/t9OAAKXoHz4N8IvJFdiSNFquGm8/SC5/7XqvG1u
          L9crJJoXiTfHEq/CjMHgqAiwx+QJ63yaaCywAbKTihPBMsuFokm5nxrtV6W265b8
          N5hsZ0RuFKbqTtWbUxdASc69Vk8G1tS6o3Pi0mW+KlVNR8pekJztyOyjveAEPTif
          Nr3HUoOnWBlQCOyxZYeMUg0fTIFDtKYAg0UDJ2mKFq+moZz9/yeci9eCmx0KVoAo
          q9Z5yqECgYEA3sGosS3+rkZK6iiNF5m2kG7HPzAj9RgQgkJWq8Mdgwp7WP96jExe
          l8C8fYK3gKdpjkJcvnE0IsUaiyl1t+B5muBZA4vvqHR1AWiLv7dBJI+zaAzNR3N7
          pP0nPfi1+4phFVh5Z7nnPF7s5776mRvwNezjXfwSZyngnuxkr8sQHm8CgYEA3Fzp
          bQXmfSVJOpwj8mUMXqd5PaWFR+JI+HnbWvY1Fe66kcumJYsjxOhbzuPqL+8GdNU5
          s0yfbqifMwUTkkgnUyWSoKh2ChXWnfZouDZUcYNbPIIXNA5VLZwWMFS8IrfjslRr
          iNJQuSxRgb2OP8iZblojteRE6r2UceSKfy9Dc6kCgYBahibQwhlSp1xAZnRYF+56
          KZqtEho6uynSVbU1Hhi7LSJNW51osIxsbTXsZ5e9H8uktVFNT2HZk3IjBZlCPWYN
          y4hBCbg+I/18sgjAw28ktYU6DqHJnKOtu/cblxwVefnUG91SitjuzsDFuPXMDO+E
          ap1Hj23HINyYmQad7g7B3wKBgQCPNJpFzZXSMk76lcoOlniJctCprU2GP5ooUBir
          bmFlVXVNlkjtERU3u8EeHKNubymE96S9zse1hEOhRmVHpThZIou9eHztZO/KS/4V
          6MjL1A+QrQIjREU6lLsewZJaBaMlmxMfIX5wOErnw6YT8Ws0ecPHSwc2felgcqNG
          sBJnsQKBgBji825uzGFKNb0UHji2mEB2gw6B/YerQz7IQPv2HziXNHoBT32ie43c
          Q3ybilwT6y5AqO7e0nNalwbdnOwFLGex4tJrAfX0sH6v0kE5ac2dmzG6wsrTRhyZ
          TxJhO18UEJQaJ87bK858IOsDJ6FY7hL4QtlAwRcUqbx8sObRepjG
          -----END RSA PRIVATE KEY-----
        clients:
        - id: argocd
          description: Argo CD
          secret: '$pbkdf2-sha512$310000$c8p78n7pUMln0jzvd4aK4Q$JNRBzwAo0ek5qKn50cFzzvE9RXV88h1wJn5KGiHrD0YKtZaR/nCb2CJPOsKaPK0hjf.9yHxzQGZziziccp6Yng'
          public: false
          authorization_policy: one_factor
          redirect_uris:
            - https://argocd.intropin.be/auth/callback
          scopes:
            - openid
            - groups
            - email
            - profile
          userinfo_signing_algorithm: none
        - id: grafana
          description: Grafana
          secret: '$pbkdf2-sha512$310000$c8p78n7pUMln0jzvd4aK4Q$JNRBzwAo0ek5qKn50cFzzvE9RXV88h1wJn5KGiHrD0YKtZaR/nCb2CJPOsKaPK0hjf.9yHxzQGZziziccp6Yng'
          public: false
          authorization_policy: one_factor
          redirect_uris:
            - https://grafana.intropin.be/login/generic_oauth
          scopes:
            - openid
            - profile
            - groups
            - email
          userinfo_signing_algorithm: none
    session:
      name: authelia_session
      # This secret can also be set using the env variables AUTHELIA_SESSION_SECRET_FILE
      secret: V9eur43qxzzsaJ7q6I7lQ29U4NV4CcdGABKvSJbzjtOeDUbMcUr11yMOJjPvjQz9
      expiration: 3600  # 1 hour
      inactivity: 300  # 5 minutes
      domain: intropin.be # Should match whatever your root protected domain is
    regulation:
      max_retries: 3
      find_time: 120
      ban_time: 300
    storage:
     encryption_key: 7TTiE99YQfT1bBic6W9Mh5HgbozhoVF8QBX8E9AsbJSA2Jux8obqWKqdH1mOvp32 # Now required
     local:
       path: /config/db.sqlite3
    notifier:
      filesystem:
        filename: /config/notification.txt
