apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia-cm
data:
  configuration.yaml: |
    ---
    theme: dark
    jwt_secret: 'secret'
    server: 
      host: 0.0.0.0
      port: 9091
    log:
      level: debug
    default_redirection_url: https://auth.intropin.be
    totp:
      issuer: authelia.com
    authentication_backend:
      file:
        path: /config/users_database.yaml
        password:
          algorithm: argon2id
          iterations: 1
          salt_length: 16
          parallelism: 8
          memory: 64
    access_control:
      default_policy: one_factor
      rules:
        - domain: home-assistant.intropin.be
          policy: one_factor
    session:
      name: authelia_session
      # This secret can also be set using the env variables AUTHELIA_SESSION_SECRET_FILE
      secret: V9eur43qxzzsaJ7q6I7lQ29U4NV4CcdGABKvSJbzjtOeDUbMcUr11yMOJjPvjQz9
      expiration: 604800 # 1 week
      inactivity: 604800 # 1 week
      domain: intropin.be # Should match whatever your root protected domain is
    regulation:
      max_retries: 3
      find_time: 120
      ban_time: 300
    storage:
     encryption_key: 7TTiE99YQfT1bBic6W9Mh5HgbozhoVF8QBX8E9AsbJSA2Jux8obqWKqdH1mOvp32 # Now required
     local:
       path: /config/db.sqlite3
    notifier:
      filesystem:
        filename: /config/notification.txt
