apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia-cm
data:
  configuration.yaml: |
    ---
    theme: dark
    jwt_secret: 'secret'
    server: 
      host: 0.0.0.0
      port: 9091
    log:
      level: debug
    default_redirection_url: https://auth.intropin.be
    totp:
      issuer: authelia.com
    authentication_backend:
      file:
        path: /config/users_database.yaml
        password:
          algorithm: argon2id
          iterations: 1
          salt_length: 16
          parallelism: 8
          memory: 64
    access_control:
      default_policy: one_factor
      rules:
        - domain: home-assistant.intropin.be
          policy: one_factor
    identity_providers:
      oidc:
        hmac_secret: this_is_a_secret_abc123abc123abc
        issuer_private_key: |
          -----BEGIN PRIVATE KEY-----
          MIIJRAIBADANBgkqhkiG9w0BAQEFAASCCS4wggkqAgEAAoICAQCPGZkdYkXwtVwP
          llaDuYFfbT9VO+pjAve9xfKnOLu9Xq7T6u1JwbO/uCI4FY/tDLU9YA9ZPHAXY3TD
          9ZIl7Fi7xBi1x0oux887YdM7vJkE7H6FxzKfQ75FYdVtChaIZJuV7leyj+n/RDvp
          vqF0hoahkJHJseQ//hrnSWjrqiJuFD1shQC1MRoiMu6mab25bOmRU6G3uOMdPiZy
          /+aB7rqBAsxOQ4HMxGBGQrG2wObQgqH9RdaW5LXvpD9SFpxUm5t2MxU2Cr3tiOUT
          NU/2x/BAZ8hyu1iKPAaaFTwNTWEwAn2XiHlC2mxXLjDdCXEUxTUlLtA37qp0sCxR
          5xLg58/t0zLo2UlimomqdnjntTS8RxmsyrZYGcyS0ILasdUxPNduH3hHRKqHgI9I
          zeOLskA420IDmO6Dh8gIEuAUAgTCn/nJ4Cfs6RMMhJ932O0dp7UyiKxxc9JaefI3
          KrDEXK4QATeq7mpTtXxaTuqEA0DPH8Kq/G8UGRaVEQl3qTFFdr40FB+gX59OOhwN
          oWeF8B/YhHEsJd2Z2ZyV1hXz4hVwqMXBzuQV068+6vU2DJVDTj+ZzV8Ga9RU2H1D
          mM2HzpH3qrEnGB7eT+1gpcYYNn7+bGmPp7cPcroznJuQ0sz4m9K4y6BZzJRGJ7K5
          Rz3kqBnBFICz2sMu9Y8Gi3N35rgTJwIDAQABAoICABPF/ejYBqxmEGmyTz5rbeDh
          nSyUwg9avnXxeiq42wRQpt1vQHOpJEKGhJVLBsoYL/ENACycqSvU2TJ8u+xT63JN
          UfwdpMwFsxvUVCu/JJvQEVmV9rztekdnEeaRIXTzsKYNOv6tsS/4iJjaImrnbdy5
          t9Nu1TMx1HDc2CEnBL6WOw3u656d7Cuz7ah+wwccxsIx6WOUKi8vwoCwiJ8FUwMh
          qlku2IA9gG96UXPcgD2+rKNCjmOSXeuBFCOD2VKS9UPmIh+yE0rVLZDeadrCskQ2
          swrbhWFbPa72kTI7XNsVSlpxMrmrVJN6tVN4YFug4SDusOSRrOnBMEFEVKZRkeMT
          mA0+Zl5HgXyWFBwQ2W2rJI3ht5iEfc2AzdL05Cee5T2ZH8Xse1WBNWFcetTLdUei
          44arLiKiv+xtu43wflkTb7n/Ge+u+XfC480c5Gsne/VuibyXR1vish9AnseQywE1
          3Jkk7oRxz/wY0W1owSyuQKfUOHrkPgLALEovl48MHZuRZZ9oZwd74REv2jUlqeCD
          2jcMrqdRyg7FuVzFWYG5wwIDJBnl7t2PQDkCC0lQYxwwIoO0uOtBpVWUzLr/t9Rg
          ODzfJY3fTBT0rmqOEH43xLkTnIwmRbhgCNn6Mb/pMyQdglVvm5Ooe3fxdNaVlcfS
          4NVf3TJV+zQn7WEDBdslAoIBAQDFubCScaZ+EnYnOfKne9b76z/8E1FFD+9dXFAl
          AF0DroPVzKCNK9tetvcSDBsIZS3NrCLbIrHXUeC8ISqOzWBP9ythyQNEwnq5oKDY
          kFVI6nu9xQ5wDqHwDv7Hq7wIKwWKfaZkUCqcDemLXib2hQjBSmIACKK+0PecFQg9
          EZaRzIVXrurFggNzaWjoX+YQaqaJW0GlaAsgrn114FPZ4wbQV+mOecSKeDyGNuPq
          K2NPBbk0TGdfue9ks+Zh6+ETrw74HduLRTzO/yXPtutfhLIhkwHRnk8aVtBYLjFl
          /DX0DhAIJZZrQ4Tgu9cUjvtP4/B50exewnaBwIeRISLUltUbAoIBAQC5RnGZLYzI
          bHDNs7uR0a60PxkvLllQH0/TriBev+ejVAfJIUXU2ri5kX+h7qaRs8sqN6o1kEol
          pjhd1kkbRcaWysoi81JrQj1mUDssD5GyKKstxl6b58czBW6YZnJ85GsWJpgnrcj+
          eCwdABhoRDGehdVGUxDdLx4n8as6moNYeH4ZWcF1zfjoJLZFTcw7Tu549OG1U3g8
          Z0+uVi/ALacXmpZA1gzCw7H/ahX4ZbzSFSAbXlvOq78+EWzL2I8eDLiSogB68GV4
          EwFlOOEmXYdTLKgWvWWtZG328w6OLQ0bq4ASG1BxyCWII84kqJZmi+RdUf0AZ1m2
          hUBtxYHGw3blAoIBAQCN3AgfSYMWeNBknGLIX0WDQOmLRaDNV/14kj6+DWCuv4q+
          3i1im9CsR8FEJYNPpqgSJCpt5pqJzajb0T/jbN5pAQETC1FZB99dRy2fsw49Xl6h
          bLxLEXSF83xAbapegd9b2YKD/jBT/ndNEqQJwrDhXSiqtYduOCcuyLg8eF37BS22
          Fz1Br2Iib8Jg1k0OAjax3dNfhSJWtFo3NFd0wDmnSSu8mQi2AEYMVV14KOD7VTPn
          ndmdCJ4FNj1YjA/UO4kV4vYdGfPi35SVTrvYsC/NfteTOW2vjBG28o1miml7TIuc
          DLu7AZpYUuyhR2RvkS57eG2KHyM/PI8HRSrkM8N5AoIBAQCDkHxWc7wHDspDqB/H
          +of+wtfVYypU9Qcwn/OolMmed6tXreLytaZ7T9C8YsWxrWTVw9WAV8fvWEuqhuI/
          FZthtPs5OmQKem0zXEHIlf21758u0DCasUoI9xCD9CvUeDd68UkW1BdobFmW9lxe
          nh5GHW9HkvDkv/LAFqKq6NHgXx/cTJpOV0crQfaU3Bvs+a3qAqrMoks9SXeRqu4Z
          n9GJt2J/BADnxSN+5gxX6Zbd79Zu2OCEr/0LzD/fuRZYFlxy88s3gcHsNELHaE6p
          eb0A2TM7gp7TM//KXuq1F1S5k11Mfkzvn1rXg+V8rqKuiyRNCE2Kndlc/N61lI0F
          YgPpAoIBAQCW0OV3vLueyVGXpMVFzrg2YkiIHxWJ1zsjRgx7jTUntxZn0wBXGPec
          JipPex+i1o/lQGfgfY6ojR2t4RsiHPqOcIETK/mAE4Qi7LqLLS4uHpKlggRnkU59
          w+/NURGv3kx2qi2Pc3qj/VfuyNcq/u+kP5rmKHPejIeCb21S+7ZftTLV/+ue2l08
          ZP2ioC50hJFY5n9LYC6hv9PTcJ1aYKEFKywxm+68jvtNs8Ji+xHvmJLr6hFpMIvB
          PJq75NHPyfkXYbUQDvAjBf/MvQr1/Yc2N1LaHiwqEHv2o6Ox98DVIhKIFEPh/0Kq
          961IXVRDhlxyYHG5O54VvDm2lll+o8K9
          -----END PRIVATE KEY-----
        access_token_lifespan: 1h
        authorize_code_lifespan: 1h
        id_token_lifespan: 1h
        refresh_token_lifespan: 90m
        enable_client_debug_messages: false
        enforce_pkce: public_clients_only
        cors:
          endpoints:
            - authorization
            - token
            - revocation
            - introspection
          allowed_origins:
            - "*"
          allowed_origins_from_client_redirect_uris: false
        clients:
        - id: argocd
          description: Argo CD
          secret: '$pbkdf2-sha512$310000$c8p78n7pUMln0jzvd4aK4Q$JNRBzwAo0ek5qKn50cFzzvE9RXV88h1wJn5KGiHrD0YKtZaR/nCb2CJPOsKaPK0hjf.9yHxzQGZziziccp6Yng'
          public: false
          authorization_policy: one_factor
          redirect_uris:
            - https://argocd.intropin.be/auth/callback
          scopes:
            - openid
            - groups
            - email
            - profile
            - offline_access
          userinfo_signing_algorithm: none
    session:
      name: authelia_session
      # This secret can also be set using the env variables AUTHELIA_SESSION_SECRET_FILE
      secret: V9eur43qxzzsaJ7q6I7lQ29U4NV4CcdGABKvSJbzjtOeDUbMcUr11yMOJjPvjQz9
      expiration: 604800 # 1 week
      inactivity: 604800 # 1 week
      domain: intropin.be # Should match whatever your root protected domain is
    regulation:
      max_retries: 3
      find_time: 120
      ban_time: 300
    storage:
     encryption_key: 7TTiE99YQfT1bBic6W9Mh5HgbozhoVF8QBX8E9AsbJSA2Jux8obqWKqdH1mOvp32 # Now required
     local:
       path: /config/db.sqlite3
    notifier:
      filesystem:
        filename: /config/notification.txt
