apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia-userdb
data:
  users_database.yaml: |
    users:
      jan:
        disabled: false
        displayname: "Jan Peters"
        # Password is authelia
        password: "$argon2id$v=19$m=65536,t=3,p=4$WmNI29/6AWArBdLdgdEZgA$wB0Uoy9K9KYZ/MR6uQ12k93RVj7h8fKKjdNv+0xN2aY"
        email: jan.peters1995@gmail.com
        groups:
          - admin
      joran:
        disabled: false
        displayname: "Joran Dirkzwager"
        password: $argon2id$v=19$m=65536,t=3,p=4$1W3KjqAfce/+/uL/D8Di2Q$zw08DqFmJo3848MuP+1WLx6WM2KYNwSJfRs1AqMJrQs
        email: joran.dirkzwager@gmail.com
        groups:
          - users
