outline:
  ingress:
    enabled: true
    annotations:
      nginx.org/websocket-services: "outline"
      cert-manager.io/cluster-issuer: "issuer"
    hosts:
      - host: &host outline.intropin.be
        paths:
          - /
    tls:
      - secretName: outline-letsencrypt-certificate
        hosts: [*host]
