outline:
  ingress:
    annotations:
      nginx.org/websocket-services: "outline"
      cert-manager.io/cluster-issuer: "issuer"
    host: &host outline.intropin.be
    tls:
      enabled: true
  env:
    URL: "https://outline.intropin.be"
    OIDC_CLIENT: "outline"
    OIDC_CLIENT_SECRET: "insecure_secret"
    OIDC_AUTH_URI: "https://auth.intropin.be/api/oidc/authorization"
    OIDC_TOKEN_URI: "https://auth.intropin.be/api/oidc/token"
    OIDC_USERINFO_URI: "https://auth.intropin.be/api/oidc/userinfo"
    OIDC_USERNAME_CLAIM: "preferred_username"
    OIDC_DISPLAY_NAME: "Authelia"
    OIDC_SCOPES: "openid offline_access profile email"
