app-template:
  defaultPodOptions:
    imagePullSecrets:
      - name: ghcr-secret

  controllers:
    # PostgreSQL Database
    postgres:
      containers:
        postgres:
          image:
            repository: postgres
            tag: 16-alpine
          env:
            POSTGRES_DB: powerbuilder_dev
            POSTGRES_USER: powerbuilder
            POSTGRES_PASSWORD: powerbuilder123
            POSTGRES_HOST_AUTH_METHOD: trust
          probes:
            readiness:
              enabled: true
              custom: true
              spec:
                exec:
                  command:
                    - /bin/sh
                    - -c
                    - pg_isready -U powerbuilder -d powerbuilder_dev
                initialDelaySeconds: 30
                periodSeconds: 10
                timeoutSeconds: 5
                failureThreshold: 5
            liveness:
              enabled: true
              custom: true
              spec:
                exec:
                  command:
                    - /bin/sh
                    - -c
                    - pg_isready -U powerbuilder -d powerbuilder_dev
                initialDelaySeconds: 30
                periodSeconds: 10
                timeoutSeconds: 5
                failureThreshold: 5

    # Backend API (Go)
    backend:
      containers:
        backend:
          image:
            repository: ghcr.io/yan-solo/powerbuilder/backend
            tag: 0.0.4
            pullPolicy: Always
          env:
            GIN_MODE: debug
            DB_HOST: powerbuilder-postgres
            DB_PORT: "5432"
            DB_USER: powerbuilder
            DB_PASSWORD: powerbuilder123
            DB_NAME: powerbuilder_dev
            DB_SSLMODE: disable
            SERVER_HOST: 0.0.0.0
            SERVER_PORT: "8080"
            CORS_ORIGINS: https://powerbuilder.intropin.be,http://spacecontrol
            JWT_SECRET: dev-jwt-secret-change-in-production

    # Frontend (Next.js)
    frontend:
      containers:
        frontend:
          image:
            repository: ghcr.io/yan-solo/powerbuilder/frontend
            tag: 0.0.4
            pullPolicy: Always
          env:
            NODE_ENV: development
            BASE_URL: https://powerbuilder.intropin.be/api
            NEXT_PUBLIC_API_URL: https://powerbuilder.intropin.be/api

  service:
    # PostgreSQL service
    postgres:
      controller: postgres
      ports:
        postgres:
          port: 5432
          targetPort: 5432

    # Backend service
    backend:
      controller: backend
      annotations:
        tailscale.com/expose: "true"
        tailscale.com/hostname: "powerbuilder-api"
      ports:
        http:
          port: 80
          targetPort: 8080

    # Frontend service
    frontend:
      controller: frontend
      annotations:
        tailscale.com/expose: "true"
        tailscale.com/hostname: "powerbuilder"
      ports:
        http:
          port: 80
          targetPort: 3000

  ingress:
    # Frontend ingress with SSL
    frontend:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
      hosts:
        - host: powerbuilder.intropin.be
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: frontend
                port: http
      tls:
        - secretName: powerbuilder-tls
          hosts:
            - powerbuilder.intropin.be

    # Backend API ingress with SSL
    backend:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
      hosts:
        - host: powerbuilder.intropin.be
          paths:
            - path: /api
              pathType: Prefix
              service:
                identifier: backend
                port: http
      tls:
        - secretName: powerbuilder-api-tls
          hosts:
            - powerbuilder.intropin.be

  persistence:
    # PostgreSQL data persistence
    postgres-data:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 5Gi
      storageClass: local-path-ssd
      advancedMounts:
        postgres:
          postgres:
            - path: /var/lib/postgresql/data
      forceRename: powerbuilder-postgres-data

    # Database initialization scripts (if needed)
    postgres-init:
      enabled: false
      type: configMap
      name: powerbuilder-postgres-init
      advancedMounts:
        postgres:
          postgres:
            - path: /docker-entrypoint-initdb.d
