---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cloudflare-ddns
spec:
  schedule: "*/5 * * * *"  # Runs every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cloudflare-ddns
            image: oznu/cloudflare-ddns
            env:
            - name: ZONE
              value: "intropin.be"
            - name: SUBDOMAIN
              value: "*"  
            - name: PROXIED
              value: "false"
            envFrom:
            - secretRef:
                name: cloudflare-secret
          restartPolicy: OnFailure
