---
app-template:
  image:
    repository: ghcr.io/yan-solo/lolbot/lolbot
    tag: latest

  # Chart requires a svc, we don't use one tho
  service:
    main:
      ports:
        http:
          port: 8123

  persistence:
    config-yaml:
      enabled: true
      type: custom
      volumeSpec:
        configMap:
          name: config
      subPath:
        - path: config.yaml
          mountPath: /usr/src/app/config.yaml

  readinessProbe: []
