app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: ghcr.io/yan-solo/lolbot/lolbot
            tag: latest
  # Chart requires a svc, we don't use one tho
  service:
    main:
      enabled: false
  persistence:
    config-yaml:
      enabled: true
      type: configMap
      name: config
      advancedMounts:
        main:
          main:
            - path: /usr/src/app/config.yaml
              readOnly: true
              subPath: config.yaml
  readinessProbe:
    enabled: false
  startupProbe:
    enabled: false
  livenessProbe:
    enabled: false
