app-template:
  defaultPodOptions:
    securityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "Always"
  controllers:
    main:
      containers:
        main:
          image:
            repository: ghcr.io/onedr0p/bazarr
            tag: 1.5.1
  service:
    main:
      controller: main
      annotations:
        tailscale.com/expose: "true"
        tailscale.com/hostname: "bazarr"
      ports:
        http:
          port: 80
          targetPort: &port 6767
  persistence:
    config:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 1Gi
      storageClass: local-path-ssd
      globalMounts:
        - path: /config
      custom-name: bazarr-config
    media:
      enabled: true
      type: persistentVolumeClaim
      existingClaim: "media"
      globalMounts:
        - path: /media
