app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: ghcr.io/onedr0p/bazarr
            tag: 1.4.0
  service:
    main:
      ports:
        http:
          port: &port 6767

  ingress:
    main:
      enabled: true
      annotations:
        nginx.org/websocket-services: "bazarr"
        nginx.ingress.kubernetes.io/auth-method: GET
        nginx.ingress.kubernetes.io/auth-url: http://authelia.core.svc.cluster.local:80/api/verify
        nginx.ingress.kubernetes.io/auth-signin: https://auth.intropin.be?rm=$request_method
        nginx.ingress.kubernetes.io/auth-response-headers: Remote-User,Remote-Name,Remote-Groups,Remote-Email
        nginx.ingress.kubernetes.io/auth-snippet: |
          proxy_set_header X-Forwarded-Method $request_method;       
        cert-manager.io/cluster-issuer: "issuer"
      hosts:
        - host: &host bazarr.intropin.be
          paths:
            - path: /
              pathType: Prefix
              service:
                port: *port
      tls:
        - secretName: bazarr-letsencrypt-certificate
          hosts: [*host]

  podSecurityContext:
    runAsUser: 568
    runAsGroup: 568
    fsGroup: 568
    fsGroupChangePolicy: "Always"

  persistence:
    config:
      enabled: true
      type: pvc
      accessMode: ReadWriteOnce
      size: 1Gi
      mountpath: /config
      storageClass: local-path-ssd

    media:
      enabled: true
      type: pvc
      existingClaim: "media"
      mountpath: /media
