local-path-provisioner-hdd:
  storageClass:
    create: false
    name: local-path-hdd
  configmap:
    name: local-path-config-hdd
  nodePathMap:
    - node: DEFAULT_PATH_FOR_NON_LISTED_NODES
      paths:
        - /var/mnt/hdd/
