---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configuration
data:
  configuration.yaml: |
    default_config:

    http:
      use_x_forwarded_for: true
      trusted_proxies: 
        - 0.0.0.0/0
      base_url: home-assistant.intropin.ba
      server_port: 8123

    sensor:
      - platform: dsmr
        host: 192.168.0.153
        port: 23
        dsmr_version: 5B
      - platform: afvalbeheer
        wastecollector: Limburg.NET
        resources:
          - restafval
          - gft
          - papier
          - pmd
        postcode: 3740
        cityname: Bilzen
        streetname: Echellaan
        streetnumber: 6
        upcomingsensor: 1
        dateformat: '%d-%m-%Y'
        dateonly: 0
        builtinicons: 1
        dutch: 0
        nameprefix: 0
