---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configuration
data:
  configuration.yaml: |
    default_config:

    http:
      use_x_forwarded_for: true
      trusted_proxies: 
        - 0.0.0.0/0
      base_url: home-assistant.intropin.ba
      server_port: 8123

    sensor:
      - platform: dsmr
        host: 192.168.0.153
        port: 23
        dsmr_version: 5B
      - afvalbeheer:
          wastecollector: Limburg.NET
          resources:
            - restafval
            - gft
            - papier
            - pmd
          postcode: 3740
          streetnumber: 6
          upcomingsensor: 1
          dateformat: '%d-%m-%Y'
          dateonly: 0
          builtinicons: 0
          builtiniconsnew: 1
          dutch: 0
